// The Minecraft Server Dashboard v2 Worker<->relay Bedrock tunnel handshake
// (epic #1540, issue #1545).
//
// Unlike mcsd.controlplane.v1 (Worker<->API) and mcsd.relay.v1 (relay<->API),
// this package is NOT served over gRPC. It is exchanged directly on a QUIC
// connection the Worker dials to the relay's Bedrock tunnel listener
// (docs/app/BEDROCK_TUNNEL.md): after the QUIC/TLS handshake completes, the
// Worker opens the first bidirectional stream and writes a TunnelHello; the
// relay answers on the same stream with a TunnelHelloAck, then closes the
// stream. Bulk RakNet traffic afterward rides QUIC DATAGRAM frames (RFC
// 9221), not streams — see the framing note on TunnelHello below.
//
// Stream wire format: each message (in either direction) is a 4-byte
// big-endian length prefix followed by that many bytes of protobuf-marshaled
// message data. This is the ONLY message exchanged on the stream in each
// direction; the stream is closed immediately after (both sides), so no
// further framing state is needed.
//
// Datagram wire format (the actual RakNet traffic, once TunnelHelloAck.accepted
// is true): every QUIC DATAGRAM frame (RFC 9221) on the connection, in either
// direction, is a 4-byte big-endian flow id followed by an opaque RakNet
// payload -- neither this package nor the relay parses RakNet itself. The
// RELAY assigns flow ids, one per distinct Bedrock client source address
// (ip:port) seen on the bound bedrock_port, for the life of that client's
// idle window; the Worker does not mint flow ids, it only echoes back the flow
// id it received on inbound datagrams when it sends the corresponding reply.
// An unrecognized flow id from the Worker (e.g. after the relay evicted an
// idle client) is dropped. Flow ids are CONNECTION-scoped: they restart from
// zero on every new QUIC connection, so the Worker MUST discard any flow-id
// state it holds when it redials -- an id carried across a reconnect would
// misroute. See docs/app/BEDROCK_TUNNEL.md for the full design: topology,
// ALPN, TLS material reuse, and the chosen datagram MTU.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcsd/bedrocktunnel/v1/bedrock_tunnel.proto

package bedrocktunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelHello is the Worker's opening message on the first bidirectional QUIC
// stream after connecting to the relay's Bedrock tunnel listener. It declares
// the credential the API minted when it dispatched
// mcsd.controlplane.v1.OpenBedrockTunnel to the Worker; the relay confirms it
// against the API via mcsd.relay.v1.RelayService.ValidateBedrockTunnel before
// binding the public UDP port (docs/app/BEDROCK_TUNNEL.md).
//
// The Worker MAY redial and resend TunnelHello with the same token after a
// transient QUIC disconnect -- unlike the per-player Java tunnel token
// (single-use, mcsd.relay.v1), this token is valid for the whole tunnel
// lifetime (open -> a matching CloseBedrockTunnel), so validation must accept
// a repeated presentation of the same (server_id, bedrock_port, token).
type TunnelHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id identifies the local server whose Bedrock (Geyser/RakNet) port
	// the Worker forwards over this tunnel. Matches
	// mcsd.controlplane.v1.OpenBedrockTunnel.server_id.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// bedrock_port is the public UDP port the relay binds and routes to this
	// connection. Matches mcsd.controlplane.v1.OpenBedrockTunnel.bedrock_port.
	BedrockPort uint32 `protobuf:"varint,2,opt,name=bedrock_port,json=bedrockPort,proto3" json:"bedrock_port,omitempty"`
	// token is the credential the API minted and the relay validates via
	// ValidateBedrockTunnel. Matches mcsd.controlplane.v1.OpenBedrockTunnel.token.
	Token         string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelHello) Reset() {
	*x = TunnelHello{}
	mi := &file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHello) ProtoMessage() {}

func (x *TunnelHello) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHello.ProtoReflect.Descriptor instead.
func (*TunnelHello) Descriptor() ([]byte, []int) {
	return file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelHello) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *TunnelHello) GetBedrockPort() uint32 {
	if x != nil {
		return x.BedrockPort
	}
	return 0
}

func (x *TunnelHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// TunnelHelloAck is the relay's reply on the same stream.
type TunnelHelloAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is true when the relay has bound (or already holds) the public
	// UDP port for the declared bedrock_port and datagram forwarding is live.
	// The Worker may then exchange RakNet datagrams (see TunnelHello's framing
	// note) until the QUIC connection closes.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reject_reason explains a refusal (invalid credential, port already bound
	// by a different connection, etc.); empty when accepted is true. The relay
	// closes the QUIC connection immediately after sending a rejecting ack (or
	// without sending one at all, for a malformed/oversized hello).
	RejectReason  string `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelHelloAck) Reset() {
	*x = TunnelHelloAck{}
	mi := &file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHelloAck) ProtoMessage() {}

func (x *TunnelHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHelloAck.ProtoReflect.Descriptor instead.
func (*TunnelHelloAck) Descriptor() ([]byte, []int) {
	return file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelHelloAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TunnelHelloAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

var File_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto protoreflect.FileDescriptor

const file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDesc = "" +
	"\n" +
	"*mcsd/bedrocktunnel/v1/bedrock_tunnel.proto\x12\x15mcsd.bedrocktunnel.v1\"c\n" +
	"\vTunnelHello\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\fbedrock_port\x18\x02 \x01(\rR\vbedrockPort\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"Q\n" +
	"\x0eTunnelHelloAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReasonB\x92\x02\n" +
	"\x19com.mcsd.bedrocktunnel.v1B\x12BedrockTunnelProtoP\x01Zkgithub.com/mmiura-2351/mc-server-dashboard-v2/relay/internal/genproto/mcsd/bedrocktunnel/v1;bedrocktunnelv1\xa2\x02\x03MBX\xaa\x02\x15Mcsd.Bedrocktunnel.V1\xca\x02\x15Mcsd\\Bedrocktunnel\\V1\xe2\x02!Mcsd\\Bedrocktunnel\\V1\\GPBMetadata\xea\x02\x17Mcsd::Bedrocktunnel::V1b\x06proto3"

var (
	file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescOnce sync.Once
	file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescData []byte
)

func file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescGZIP() []byte {
	file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescOnce.Do(func() {
		file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDesc), len(file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDesc)))
	})
	return file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDescData
}

var file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_goTypes = []any{
	(*TunnelHello)(nil),    // 0: mcsd.bedrocktunnel.v1.TunnelHello
	(*TunnelHelloAck)(nil), // 1: mcsd.bedrocktunnel.v1.TunnelHelloAck
}
var file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_init() }
func file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_init() {
	if File_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDesc), len(file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_goTypes,
		DependencyIndexes: file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_depIdxs,
		MessageInfos:      file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_msgTypes,
	}.Build()
	File_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto = out.File
	file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_goTypes = nil
	file_mcsd_bedrocktunnel_v1_bedrock_tunnel_proto_depIdxs = nil
}
