# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcsd.controlplane.v1 import control_plane_pb2 as mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcsd/controlplane/v1/control_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """WorkerService is the only control-plane service. Workers dial the API and open
    the persistent stream; the API never dials a Worker (Workers have no inbound
    exposure, REQUIREMENTS.md Section 5.1).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/mcsd.controlplane.v1.WorkerService/Session',
                request_serializer=mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2.WorkerMessage.SerializeToString,
                response_deserializer=mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2.ApiMessage.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """WorkerService is the only control-plane service. Workers dial the API and open
    the persistent stream; the API never dials a Worker (Workers have no inbound
    exposure, REQUIREMENTS.md Section 5.1).
    """

    def Session(self, request_iterator, context):
        """Session is the single bidirectional stream for one connected Worker. The
        Worker sends WorkerMessage values (starting with a Register), the API sends
        ApiMessage values (commands). Closing the stream disconnects the Worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2.WorkerMessage.FromString,
                    response_serializer=mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2.ApiMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcsd.controlplane.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcsd.controlplane.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """WorkerService is the only control-plane service. Workers dial the API and open
    the persistent stream; the API never dials a Worker (Workers have no inbound
    exposure, REQUIREMENTS.md Section 5.1).
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mcsd.controlplane.v1.WorkerService/Session',
            mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2.WorkerMessage.SerializeToString,
            mcsd_dot_controlplane_dot_v1_dot_control__plane__pb2.ApiMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
