"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The Minecraft Server Dashboard v2 control-plane contract.

A single Worker-initiated gRPC bidirectional stream multiplexes API->Worker
commands and Worker->API events (REQUIREMENTS.md Section 5.1). Registration is
the first Worker->API message; thereafter the stream carries commands,
command results, and asynchronous events (status / log / metrics / heartbeat).

See docs/app/CONTROL_PLANE.md for the stream lifecycle, message-flow diagrams,
and the requirement-by-requirement mapping. This file is the binding contract;
the doc explains it.
"""

from collections import abc as _abc
from grpc import aio as _aio
from mcsd.controlplane.v1 import control_plane_pb2 as _control_plane_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class WorkerServiceStub:
    """WorkerService is the only control-plane service. Workers dial the API and open
    the persistent stream; the API never dials a Worker (Workers have no inbound
    exposure, REQUIREMENTS.md Section 5.1).
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WorkerServiceAsyncStub: ...
    Session: _grpc.StreamStreamMultiCallable[_control_plane_pb2.WorkerMessage, _control_plane_pb2.ApiMessage]
    """Session is the single bidirectional stream for one connected Worker. The
    Worker sends WorkerMessage values (starting with a Register), the API sends
    ApiMessage values (commands). Closing the stream disconnects the Worker.
    """

@_typing.type_check_only
class WorkerServiceAsyncStub(WorkerServiceStub):
    """WorkerService is the only control-plane service. Workers dial the API and open
    the persistent stream; the API never dials a Worker (Workers have no inbound
    exposure, REQUIREMENTS.md Section 5.1).
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Session: _aio.StreamStreamMultiCallable[_control_plane_pb2.WorkerMessage, _control_plane_pb2.ApiMessage]  # type: ignore[assignment]
    """Session is the single bidirectional stream for one connected Worker. The
    Worker sends WorkerMessage values (starting with a Register), the API sends
    ApiMessage values (commands). Closing the stream disconnects the Worker.
    """

class WorkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """WorkerService is the only control-plane service. Workers dial the API and open
    the persistent stream; the API never dials a Worker (Workers have no inbound
    exposure, REQUIREMENTS.md Section 5.1).
    """

    @_abc_1.abstractmethod
    def Session(
        self,
        request_iterator: _MaybeAsyncIterator[_control_plane_pb2.WorkerMessage],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_control_plane_pb2.ApiMessage], _abc.AsyncIterator[_control_plane_pb2.ApiMessage]]:
        """Session is the single bidirectional stream for one connected Worker. The
        Worker sends WorkerMessage values (starting with a Register), the API sends
        ApiMessage values (commands). Closing the stream disconnects the Worker.
        """

def add_WorkerServiceServicer_to_server(servicer: WorkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
