"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The Minecraft Server Dashboard v2 control-plane contract.

A single Worker-initiated gRPC bidirectional stream multiplexes API->Worker
commands and Worker->API events (REQUIREMENTS.md Section 5.1). Registration is
the first Worker->API message; thereafter the stream carries commands,
command results, and asynchronous events (status / log / metrics / heartbeat).

See docs/app/CONTROL_PLANE.md for the stream lifecycle, message-flow diagrams,
and the requirement-by-requirement mapping. This file is the binding contract;
the doc explains it.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ExecutionDriverKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ExecutionDriverKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ExecutionDriverKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EXECUTION_DRIVER_KIND_UNSPECIFIED: _ExecutionDriverKind.ValueType  # 0
    EXECUTION_DRIVER_KIND_HOST_PROCESS: _ExecutionDriverKind.ValueType  # 1
    EXECUTION_DRIVER_KIND_CONTAINER: _ExecutionDriverKind.ValueType  # 2

class ExecutionDriverKind(_ExecutionDriverKind, metaclass=_ExecutionDriverKindEnumTypeWrapper):
    """ExecutionDriverKind enumerates the execution backends (FR-EXE-2, FR-EXE-4)."""

EXECUTION_DRIVER_KIND_UNSPECIFIED: ExecutionDriverKind.ValueType  # 0
EXECUTION_DRIVER_KIND_HOST_PROCESS: ExecutionDriverKind.ValueType  # 1
EXECUTION_DRIVER_KIND_CONTAINER: ExecutionDriverKind.ValueType  # 2
Global___ExecutionDriverKind: _TypeAlias = ExecutionDriverKind  # noqa: Y015

class _CommandErrorCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CommandErrorCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CommandErrorCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    COMMAND_ERROR_CODE_UNSPECIFIED: _CommandErrorCode.ValueType  # 0
    COMMAND_ERROR_CODE_SERVER_NOT_FOUND: _CommandErrorCode.ValueType  # 1
    """The target server is not known to this Worker."""
    COMMAND_ERROR_CODE_INVALID_STATE: _CommandErrorCode.ValueType  # 2
    """The command is invalid for the server's current state (e.g. start a
    running server, RCON on a stopped one).
    """
    COMMAND_ERROR_CODE_DRIVER_UNAVAILABLE: _CommandErrorCode.ValueType  # 3
    """The requested execution driver is not available on this Worker."""
    COMMAND_ERROR_CODE_FILE_ACCESS_DENIED: _CommandErrorCode.ValueType  # 4
    """A file path was rejected (traversal / not found / not permitted)."""
    COMMAND_ERROR_CODE_TRANSFER_FAILED: _CommandErrorCode.ValueType  # 5
    """A hydrate/snapshot data-plane transfer failed."""
    COMMAND_ERROR_CODE_INTERNAL: _CommandErrorCode.ValueType  # 6
    """The Worker failed to apply the command for an unclassified reason."""

class CommandErrorCode(_CommandErrorCode, metaclass=_CommandErrorCodeEnumTypeWrapper):
    """CommandErrorCode classifies a command failure."""

COMMAND_ERROR_CODE_UNSPECIFIED: CommandErrorCode.ValueType  # 0
COMMAND_ERROR_CODE_SERVER_NOT_FOUND: CommandErrorCode.ValueType  # 1
"""The target server is not known to this Worker."""
COMMAND_ERROR_CODE_INVALID_STATE: CommandErrorCode.ValueType  # 2
"""The command is invalid for the server's current state (e.g. start a
running server, RCON on a stopped one).
"""
COMMAND_ERROR_CODE_DRIVER_UNAVAILABLE: CommandErrorCode.ValueType  # 3
"""The requested execution driver is not available on this Worker."""
COMMAND_ERROR_CODE_FILE_ACCESS_DENIED: CommandErrorCode.ValueType  # 4
"""A file path was rejected (traversal / not found / not permitted)."""
COMMAND_ERROR_CODE_TRANSFER_FAILED: CommandErrorCode.ValueType  # 5
"""A hydrate/snapshot data-plane transfer failed."""
COMMAND_ERROR_CODE_INTERNAL: CommandErrorCode.ValueType  # 6
"""The Worker failed to apply the command for an unclassified reason."""
Global___CommandErrorCode: _TypeAlias = CommandErrorCode  # noqa: Y015

class _ServerState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ServerStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ServerState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SERVER_STATE_UNSPECIFIED: _ServerState.ValueType  # 0
    SERVER_STATE_STARTING: _ServerState.ValueType  # 1
    SERVER_STATE_RUNNING: _ServerState.ValueType  # 2
    SERVER_STATE_STOPPING: _ServerState.ValueType  # 3
    SERVER_STATE_STOPPED: _ServerState.ValueType  # 4
    SERVER_STATE_RESTARTING: _ServerState.ValueType  # 5
    SERVER_STATE_CRASHED: _ServerState.ValueType  # 6

class ServerState(_ServerState, metaclass=_ServerStateEnumTypeWrapper):
    """ServerState is the observed runtime state of a server (FR-SRV-4:
    running / stopped / starting / crashed, plus the in-between transitions and a
    restarting state the lifecycle commands produce). This is the full set of
    values a Worker can report. The API caches the last-reported value in
    Server.observed_state (DATABASE.md); that column also allows "unknown", which
    is an API-side inference (set when the owning Worker disconnects), never
    reported by a Worker, so it is intentionally not a value here.
    """

SERVER_STATE_UNSPECIFIED: ServerState.ValueType  # 0
SERVER_STATE_STARTING: ServerState.ValueType  # 1
SERVER_STATE_RUNNING: ServerState.ValueType  # 2
SERVER_STATE_STOPPING: ServerState.ValueType  # 3
SERVER_STATE_STOPPED: ServerState.ValueType  # 4
SERVER_STATE_RESTARTING: ServerState.ValueType  # 5
SERVER_STATE_CRASHED: ServerState.ValueType  # 6
Global___ServerState: _TypeAlias = ServerState  # noqa: Y015

class _LogStream:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LogStreamEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LogStream.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOG_STREAM_UNSPECIFIED: _LogStream.ValueType  # 0
    LOG_STREAM_STDOUT: _LogStream.ValueType  # 1
    LOG_STREAM_STDERR: _LogStream.ValueType  # 2

class LogStream(_LogStream, metaclass=_LogStreamEnumTypeWrapper):
    """LogStream identifies which output stream a LogLine came from."""

LOG_STREAM_UNSPECIFIED: LogStream.ValueType  # 0
LOG_STREAM_STDOUT: LogStream.ValueType  # 1
LOG_STREAM_STDERR: LogStream.ValueType  # 2
Global___LogStream: _TypeAlias = LogStream  # noqa: Y015

@_typing.final
class WorkerMessage(_message.Message):
    """---------------------------------------------------------------------------
    Envelopes
    ---------------------------------------------------------------------------

    WorkerMessage is every message a Worker sends to the API over the stream.
    Exactly one payload field is set.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    EMITTED_AT_FIELD_NUMBER: _builtins.int
    REGISTER_FIELD_NUMBER: _builtins.int
    COMMAND_RESULT_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    correlation_id: _builtins.str
    """correlation_id ties a flow together end to end (REQUIREMENTS.md NFR-OBS-1).
    For a command_result it MUST equal the originating ApiCommand.command_id so
    the API can match a result to its command. For unsolicited events it is a
    fresh id the API can log and trace.
    """
    @_builtins.property
    def emitted_at(self) -> _timestamp_pb2.Timestamp:
        """emitted_at is the Worker's clock reading when the message was produced."""

    @_builtins.property
    def register(self) -> Global___Register:
        """Register MUST be the first message on a fresh stream (FR-WRK-1)."""

    @_builtins.property
    def command_result(self) -> Global___CommandResult:
        """CommandResult answers an ApiCommand (success or error)."""

    @_builtins.property
    def event(self) -> Global___Event:
        """Event is an asynchronous status / log / metrics / heartbeat report."""

    def __init__(
        self,
        *,
        correlation_id: _builtins.str = ...,
        emitted_at: _timestamp_pb2.Timestamp | None = ...,
        register: Global___Register | None = ...,
        command_result: Global___CommandResult | None = ...,
        event: Global___Event | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command_result", b"command_result", "emitted_at", b"emitted_at", "event", b"event", "payload", b"payload", "register", b"register"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_result", b"command_result", "correlation_id", b"correlation_id", "emitted_at", b"emitted_at", "event", b"event", "payload", b"payload", "register", b"register"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["register", "command_result", "event"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___WorkerMessage: _TypeAlias = WorkerMessage  # noqa: Y015

@_typing.final
class ApiMessage(_message.Message):
    """ApiMessage is every message the API sends to a Worker over the stream.
    Exactly one payload field is set.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    SENT_AT_FIELD_NUMBER: _builtins.int
    REGISTER_ACK_FIELD_NUMBER: _builtins.int
    API_COMMAND_FIELD_NUMBER: _builtins.int
    correlation_id: _builtins.str
    """correlation_id traces the flow (REQUIREMENTS.md NFR-OBS-1). For a command it
    is the same value as the command's command_id; for register_ack it echoes
    the Register message's correlation_id.
    """
    @_builtins.property
    def sent_at(self) -> _timestamp_pb2.Timestamp:
        """sent_at is the API's clock reading when the message was produced."""

    @_builtins.property
    def register_ack(self) -> Global___RegisterAck:
        """RegisterAck accepts or rejects a Register (sent first, in response)."""

    @_builtins.property
    def api_command(self) -> Global___ApiCommand:
        """ApiCommand instructs the Worker to act on a server."""

    def __init__(
        self,
        *,
        correlation_id: _builtins.str = ...,
        sent_at: _timestamp_pb2.Timestamp | None = ...,
        register_ack: Global___RegisterAck | None = ...,
        api_command: Global___ApiCommand | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["api_command", b"api_command", "payload", b"payload", "register_ack", b"register_ack", "sent_at", b"sent_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_command", b"api_command", "correlation_id", b"correlation_id", "payload", b"payload", "register_ack", b"register_ack", "sent_at", b"sent_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["register_ack", "api_command"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ApiMessage: _TypeAlias = ApiMessage  # noqa: Y015

@_typing.final
class Register(_message.Message):
    """---------------------------------------------------------------------------
    Registration & capability advertisement (FR-WRK-1)
    ---------------------------------------------------------------------------

    Register is the Worker's opening message: who it is and what it can run.
    """

    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    WORKER_VERSION_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    """worker_id is the stable identifier the Worker registers under
    (CONFIGURATION.md Section 6.1 worker.id).
    """
    worker_version: _builtins.str
    """worker_version is the Worker build/release string, for fleet visibility."""
    @_builtins.property
    def capabilities(self) -> Global___WorkerCapabilities:
        """capabilities advertises the drivers and resources the API's greedy
        placement filters on (FR-WRK-3).
        """

    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        worker_version: _builtins.str = ...,
        capabilities: Global___WorkerCapabilities | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "worker_id", b"worker_id", "worker_version", b"worker_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Register: _TypeAlias = Register  # noqa: Y015

@_typing.final
class WorkerCapabilities(_message.Message):
    """WorkerCapabilities is what a Worker advertises at registration (FR-WRK-1)."""

    DESCRIPTOR: _descriptor.Descriptor

    DRIVERS_FIELD_NUMBER: _builtins.int
    MAX_SERVERS_FIELD_NUMBER: _builtins.int
    RESOURCES_FIELD_NUMBER: _builtins.int
    max_servers: _builtins.int
    """max_servers is the Worker's free-capacity hint for placement; 0 means "no
    advertised cap" (CONFIGURATION.md Section 6.2 worker.max_servers).
    """
    @_builtins.property
    def drivers(self) -> _containers.RepeatedScalarFieldContainer[Global___ExecutionDriverKind.ValueType]:
        """drivers is the set of execution backends this Worker offers
        (CONFIGURATION.md Section 6.2 worker.drivers).
        """

    @_builtins.property
    def resources(self) -> Global___HostResources:
        """resources advertises host resources for placement and monitoring."""

    def __init__(
        self,
        *,
        drivers: _abc.Iterable[Global___ExecutionDriverKind.ValueType] | None = ...,
        max_servers: _builtins.int = ...,
        resources: Global___HostResources | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resources", b"resources"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["drivers", b"drivers", "max_servers", b"max_servers", "resources", b"resources"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WorkerCapabilities: _TypeAlias = WorkerCapabilities  # noqa: Y015

@_typing.final
class HostResources(_message.Message):
    """HostResources is a coarse description of a Worker host's resources."""

    DESCRIPTOR: _descriptor.Descriptor

    CPU_CORES_FIELD_NUMBER: _builtins.int
    MEMORY_BYTES_FIELD_NUMBER: _builtins.int
    cpu_cores: _builtins.int
    """cpu_cores is the number of logical CPUs available to the Worker."""
    memory_bytes: _builtins.int
    """memory_bytes is the total memory available to the Worker."""
    def __init__(
        self,
        *,
        cpu_cores: _builtins.int = ...,
        memory_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cpu_cores", b"cpu_cores", "memory_bytes", b"memory_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HostResources: _TypeAlias = HostResources  # noqa: Y015

@_typing.final
class RegisterAck(_message.Message):
    """RegisterAck accepts or rejects a registration."""

    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    HEARTBEAT_INTERVAL_FIELD_NUMBER: _builtins.int
    REJECTION_REASON_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    """accepted is true when the API admitted this Worker into the registry."""
    rejection_reason: _builtins.str
    """rejection_reason explains a refusal (e.g. bad credential, duplicate id);
    empty when accepted is true.
    """
    @_builtins.property
    def heartbeat_interval(self) -> _duration_pb2.Duration:
        """heartbeat_interval is how often the API expects a HEARTBEAT event. The API
        marks the Worker disconnected after it misses heartbeats past its liveness
        window (CONFIGURATION.md Section 5.1 control.heartbeat_timeout_seconds,
        FR-WRK-2).
        """

    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
        heartbeat_interval: _duration_pb2.Duration | None = ...,
        rejection_reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["heartbeat_interval", b"heartbeat_interval"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted", "heartbeat_interval", b"heartbeat_interval", "rejection_reason", b"rejection_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterAck: _TypeAlias = RegisterAck  # noqa: Y015

@_typing.final
class ApiCommand(_message.Message):
    """---------------------------------------------------------------------------
    Commands: API -> Worker (FR-SRV-2, FR-SRV-5, Section 6.9, Section 7.2)
    ---------------------------------------------------------------------------

    ApiCommand is one instruction the Worker must act on and answer with a
    CommandResult carrying the same command_id.
    """

    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_ID_FIELD_NUMBER: _builtins.int
    SERVER_ID_FIELD_NUMBER: _builtins.int
    START_FIELD_NUMBER: _builtins.int
    STOP_FIELD_NUMBER: _builtins.int
    RESTART_FIELD_NUMBER: _builtins.int
    SERVER_COMMAND_FIELD_NUMBER: _builtins.int
    HYDRATE_FIELD_NUMBER: _builtins.int
    SNAPSHOT_FIELD_NUMBER: _builtins.int
    READ_FILE_FIELD_NUMBER: _builtins.int
    EDIT_FILE_FIELD_NUMBER: _builtins.int
    command_id: _builtins.str
    """command_id correlates this command with its CommandResult
    (REQUIREMENTS.md NFR-OBS-1).
    """
    server_id: _builtins.str
    """server_id is the API's identifier for the target server. Set for every
    per-server command; empty only for future fleet-wide commands.
    """
    @_builtins.property
    def start(self) -> Global___StartServer: ...
    @_builtins.property
    def stop(self) -> Global___StopServer: ...
    @_builtins.property
    def restart(self) -> Global___RestartServer: ...
    @_builtins.property
    def server_command(self) -> Global___ServerCommand:
        """ServerCommand forwards an RCON / console command (FR-SRV-5)."""

    @_builtins.property
    def hydrate(self) -> Global___HydrateTrigger:
        """Hydrate triggers the Worker to pull the working set from the API data
        plane before launch (FR-DATA-4). The bulk transfer itself rides the HTTP
        data plane, not this stream (Section 5.2).
        """

    @_builtins.property
    def snapshot(self) -> Global___SnapshotTrigger:
        """Snapshot triggers the Worker to push its working set back to the API data
        plane (FR-DATA-4, FR-DATA-7).
        """

    @_builtins.property
    def read_file(self) -> Global___ReadFile:
        """ReadFile reads from a running server's live working set (Section 7.2)."""

    @_builtins.property
    def edit_file(self) -> Global___EditFile:
        """EditFile writes to a running server's live working set (Section 7.2)."""

    def __init__(
        self,
        *,
        command_id: _builtins.str = ...,
        server_id: _builtins.str = ...,
        start: Global___StartServer | None = ...,
        stop: Global___StopServer | None = ...,
        restart: Global___RestartServer | None = ...,
        server_command: Global___ServerCommand | None = ...,
        hydrate: Global___HydrateTrigger | None = ...,
        snapshot: Global___SnapshotTrigger | None = ...,
        read_file: Global___ReadFile | None = ...,
        edit_file: Global___EditFile | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "edit_file", b"edit_file", "hydrate", b"hydrate", "read_file", b"read_file", "restart", b"restart", "server_command", b"server_command", "snapshot", b"snapshot", "start", b"start", "stop", b"stop"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "command_id", b"command_id", "edit_file", b"edit_file", "hydrate", b"hydrate", "read_file", b"read_file", "restart", b"restart", "server_command", b"server_command", "server_id", b"server_id", "snapshot", b"snapshot", "start", b"start", "stop", b"stop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_command: _TypeAlias = _typing.Literal["start", "stop", "restart", "server_command", "hydrate", "snapshot", "read_file", "edit_file"]  # noqa: Y015
    _WhichOneofArgType_command: _TypeAlias = _typing.Literal["command", b"command"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_command) -> _WhichOneofReturnType_command | None: ...

Global___ApiCommand: _TypeAlias = ApiCommand  # noqa: Y015

@_typing.final
class StartServer(_message.Message):
    """StartServer launches a server on the Worker. Hydrate (FR-DATA-4) precedes the
    launch; the API issues a HydrateTrigger first, then StartServer.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DRIVER_FIELD_NUMBER: _builtins.int
    JAR_RELPATH_FIELD_NUMBER: _builtins.int
    MINECRAFT_VERSION_FIELD_NUMBER: _builtins.int
    driver: Global___ExecutionDriverKind.ValueType
    """driver is the execution backend to use; it MUST be one the Worker
    advertised (FR-EXE-3 fixes it per server).
    """
    jar_relpath: _builtins.str
    """jar_relpath is the server JAR path inside the hydrated working set. The API
    owns JAR retrieval and ships it via hydrate; the Worker never fetches it
    (ARCHITECTURE.md Section 7.3).
    """
    minecraft_version: _builtins.str
    """minecraft_version lets the Worker pick the Java runtime (FR-EXE-5); the API
    does not choose the java binary.
    """
    def __init__(
        self,
        *,
        driver: Global___ExecutionDriverKind.ValueType = ...,
        jar_relpath: _builtins.str = ...,
        minecraft_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["driver", b"driver", "jar_relpath", b"jar_relpath", "minecraft_version", b"minecraft_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartServer: _TypeAlias = StartServer  # noqa: Y015

@_typing.final
class StopServer(_message.Message):
    """StopServer stops a running server. A graceful stop takes an event-driven
    snapshot before exit (FR-DATA-7); set force to skip the graceful path.
    """

    DESCRIPTOR: _descriptor.Descriptor

    FORCE_FIELD_NUMBER: _builtins.int
    force: _builtins.bool
    def __init__(
        self,
        *,
        force: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["force", b"force"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopServer: _TypeAlias = StopServer  # noqa: Y015

@_typing.final
class RestartServer(_message.Message):
    """RestartServer stops then starts the server in place."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RestartServer: _TypeAlias = RestartServer  # noqa: Y015

@_typing.final
class ServerCommand(_message.Message):
    """ServerCommand forwards a console / RCON command to the running server
    (FR-SRV-5). The output is returned in the CommandResult.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LINE_FIELD_NUMBER: _builtins.int
    line: _builtins.str
    """line is the raw command line sent to the server console (e.g. "say hi")."""
    def __init__(
        self,
        *,
        line: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["line", b"line"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerCommand: _TypeAlias = ServerCommand  # noqa: Y015

@_typing.final
class HydrateTrigger(_message.Message):
    """HydrateTrigger tells the Worker to pull a server's working set from the API
    data plane into local scratch (FR-DATA-4). transfer_url and transfer_token
    address the API-terminated HTTP data-plane endpoint (Section 5.2); the bulk
    bytes never traverse this stream.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TRANSFER_URL_FIELD_NUMBER: _builtins.int
    TRANSFER_TOKEN_FIELD_NUMBER: _builtins.int
    transfer_url: _builtins.str
    transfer_token: _builtins.str
    """transfer_token is a short-lived credential authorizing this one transfer."""
    def __init__(
        self,
        *,
        transfer_url: _builtins.str = ...,
        transfer_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["transfer_token", b"transfer_token", "transfer_url", b"transfer_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HydrateTrigger: _TypeAlias = HydrateTrigger  # noqa: Y015

@_typing.final
class SnapshotTrigger(_message.Message):
    """SnapshotTrigger tells the Worker to push its working set back to the API data
    plane (FR-DATA-4, FR-DATA-7). For a running server the Worker performs
    save-all over RCON first (Section 6.9).
    """

    DESCRIPTOR: _descriptor.Descriptor

    TRANSFER_URL_FIELD_NUMBER: _builtins.int
    TRANSFER_TOKEN_FIELD_NUMBER: _builtins.int
    transfer_url: _builtins.str
    transfer_token: _builtins.str
    def __init__(
        self,
        *,
        transfer_url: _builtins.str = ...,
        transfer_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["transfer_token", b"transfer_token", "transfer_url", b"transfer_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SnapshotTrigger: _TypeAlias = SnapshotTrigger  # noqa: Y015

@_typing.final
class ReadFile(_message.Message):
    """ReadFile reads a path from a running server's live working set (Section 7.2).
    Path-traversal protection is enforced on the Worker side (FR-FILE-4).
    """

    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """path is relative to the server's working-set root."""
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadFile: _TypeAlias = ReadFile  # noqa: Y015

@_typing.final
class EditFile(_message.Message):
    """EditFile writes content to a path in a running server's live working set
    (Section 7.2). Path-traversal protection is enforced on the Worker side
    (FR-FILE-4).
    """

    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    content: _builtins.bytes
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditFile: _TypeAlias = EditFile  # noqa: Y015

@_typing.final
class CommandResult(_message.Message):
    """---------------------------------------------------------------------------
    Command results: Worker -> API
    ---------------------------------------------------------------------------

    CommandResult answers exactly one ApiCommand. The enclosing WorkerMessage's
    correlation_id equals the command's command_id.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    COMMAND_OUTPUT_FIELD_NUMBER: _builtins.int
    FILE_CONTENT_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    """success is true when the command was applied without error."""
    command_output: _builtins.str
    """command_output is the console/RCON output for a ServerCommand."""
    file_content: _builtins.bytes
    """file_content is the bytes read for a ReadFile."""
    @_builtins.property
    def error(self) -> Global___CommandError:
        """error describes the failure; absent when success is true."""

    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: Global___CommandError | None = ...,
        command_output: _builtins.str = ...,
        file_content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command_output", b"command_output", "error", b"error", "file_content", b"file_content", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_output", b"command_output", "error", b"error", "file_content", b"file_content", "result", b"result", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["command_output", "file_content"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___CommandResult: _TypeAlias = CommandResult  # noqa: Y015

@_typing.final
class CommandError(_message.Message):
    """CommandError reports why a command failed (NFR-OBS-1 error reporting)."""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    code: Global___CommandErrorCode.ValueType
    """code classifies the failure for programmatic handling."""
    message: _builtins.str
    """message is a human-readable explanation for logs and operators."""
    def __init__(
        self,
        *,
        code: Global___CommandErrorCode.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandError: _TypeAlias = CommandError  # noqa: Y015

@_typing.final
class Event(_message.Message):
    """---------------------------------------------------------------------------
    Events: Worker -> API (FR-MON-1..3, FR-WRK-2, FR-SRV-4)
    ---------------------------------------------------------------------------

    Event is an asynchronous report from a Worker, not tied to a command.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SERVER_ID_FIELD_NUMBER: _builtins.int
    STATUS_CHANGE_FIELD_NUMBER: _builtins.int
    LOG_LINE_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    HEARTBEAT_FIELD_NUMBER: _builtins.int
    server_id: _builtins.str
    """server_id scopes the event to a server; empty for Worker-wide events such
    as a heartbeat.
    """
    @_builtins.property
    def status_change(self) -> Global___StatusChange:
        """StatusChange reports an observed server-state transition (FR-SRV-4,
        FR-MON-1).
        """

    @_builtins.property
    def log_line(self) -> Global___LogLine:
        """LogLine streams a line of server output (FR-MON-2)."""

    @_builtins.property
    def metrics(self) -> Global___Metrics:
        """Metrics reports basic runtime metrics (FR-MON-3)."""

    @_builtins.property
    def heartbeat(self) -> Global___Heartbeat:
        """Heartbeat is the liveness signal (FR-WRK-2)."""

    def __init__(
        self,
        *,
        server_id: _builtins.str = ...,
        status_change: Global___StatusChange | None = ...,
        log_line: Global___LogLine | None = ...,
        metrics: Global___Metrics | None = ...,
        heartbeat: Global___Heartbeat | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "heartbeat", b"heartbeat", "log_line", b"log_line", "metrics", b"metrics", "status_change", b"status_change"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "heartbeat", b"heartbeat", "log_line", b"log_line", "metrics", b"metrics", "server_id", b"server_id", "status_change", b"status_change"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["status_change", "log_line", "metrics", "heartbeat"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class StatusChange(_message.Message):
    """StatusChange reports the Worker's observed runtime state for a server
    (FR-SRV-4). The API holds desired state; this is the observed side.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    state: Global___ServerState.ValueType
    detail: _builtins.str
    """detail optionally explains the transition (e.g. a crash reason)."""
    def __init__(
        self,
        *,
        state: Global___ServerState.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusChange: _TypeAlias = StatusChange  # noqa: Y015

@_typing.final
class LogLine(_message.Message):
    """LogLine is a single line of a server's console output (FR-MON-2)."""

    DESCRIPTOR: _descriptor.Descriptor

    LINE_FIELD_NUMBER: _builtins.int
    STREAM_FIELD_NUMBER: _builtins.int
    line: _builtins.str
    """line is the raw log text without a trailing newline."""
    stream: Global___LogStream.ValueType
    """stream distinguishes stdout from stderr."""
    def __init__(
        self,
        *,
        line: _builtins.str = ...,
        stream: Global___LogStream.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["line", b"line", "stream", b"stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LogLine: _TypeAlias = LogLine  # noqa: Y015

@_typing.final
class Metrics(_message.Message):
    """Metrics is a basic runtime metrics sample for a server (FR-MON-3). Fields are
    best-effort; a Worker that cannot measure one leaves it zero.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CPU_MILLIS_FIELD_NUMBER: _builtins.int
    MEMORY_BYTES_FIELD_NUMBER: _builtins.int
    PLAYER_COUNT_FIELD_NUMBER: _builtins.int
    cpu_millis: _builtins.int
    """cpu_millis is CPU usage in thousandths of a core (1000 == one full core)."""
    memory_bytes: _builtins.int
    """memory_bytes is the resident memory of the server process."""
    player_count: _builtins.int
    """player_count is the number of connected players, when known."""
    def __init__(
        self,
        *,
        cpu_millis: _builtins.int = ...,
        memory_bytes: _builtins.int = ...,
        player_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cpu_millis", b"cpu_millis", "memory_bytes", b"memory_bytes", "player_count", b"player_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Metrics: _TypeAlias = Metrics  # noqa: Y015

@_typing.final
class Heartbeat(_message.Message):
    """Heartbeat is the periodic liveness signal (FR-WRK-2). Its cadence is the
    heartbeat_interval the API returned in RegisterAck.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Heartbeat: _TypeAlias = Heartbeat  # noqa: Y015
