// The Minecraft Server Dashboard v2 control-plane contract.
//
// A single Worker-initiated gRPC bidirectional stream multiplexes API->Worker
// commands and Worker->API events (REQUIREMENTS.md Section 5.1). Registration is
// the first Worker->API message; thereafter the stream carries commands,
// command results, and asynchronous events (status / log / metrics / heartbeat).
//
// See docs/app/CONTROL_PLANE.md for the stream lifecycle, message-flow diagrams,
// and the requirement-by-requirement mapping. This file is the binding contract;
// the doc explains it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mcsd/controlplane/v1/control_plane.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Session_FullMethodName = "/mcsd.controlplane.v1.WorkerService/Session"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService is the only control-plane service. Workers dial the API and open
// the persistent stream; the API never dials a Worker (Workers have no inbound
// exposure, REQUIREMENTS.md Section 5.1).
type WorkerServiceClient interface {
	// Session is the single bidirectional stream for one connected Worker. The
	// Worker sends WorkerMessage values (starting with a Register), the API sends
	// ApiMessage values (commands). Closing the stream disconnects the Worker.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ApiMessage], error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ApiMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ApiMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_SessionClient = grpc.BidiStreamingClient[WorkerMessage, ApiMessage]

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService is the only control-plane service. Workers dial the API and open
// the persistent stream; the API never dials a Worker (Workers have no inbound
// exposure, REQUIREMENTS.md Section 5.1).
type WorkerServiceServer interface {
	// Session is the single bidirectional stream for one connected Worker. The
	// Worker sends WorkerMessage values (starting with a Register), the API sends
	// ApiMessage values (commands). Closing the stream disconnects the Worker.
	Session(grpc.BidiStreamingServer[WorkerMessage, ApiMessage]) error
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Session(grpc.BidiStreamingServer[WorkerMessage, ApiMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).Session(&grpc.GenericServerStream[WorkerMessage, ApiMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_SessionServer = grpc.BidiStreamingServer[WorkerMessage, ApiMessage]

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcsd.controlplane.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _WorkerService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mcsd/controlplane/v1/control_plane.proto",
}
