// The Minecraft Server Dashboard v2 control-plane contract.
//
// A single Worker-initiated gRPC bidirectional stream multiplexes API->Worker
// commands and Worker->API events (REQUIREMENTS.md Section 5.1). Registration is
// the first Worker->API message; thereafter the stream carries commands,
// command results, and asynchronous events (status / log / metrics / heartbeat).
//
// See docs/app/CONTROL_PLANE.md for the stream lifecycle, message-flow diagrams,
// and the requirement-by-requirement mapping. This file is the binding contract;
// the doc explains it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcsd/controlplane/v1/control_plane.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionDriverKind enumerates the execution backends (FR-EXE-2, FR-EXE-4).
type ExecutionDriverKind int32

const (
	ExecutionDriverKind_EXECUTION_DRIVER_KIND_UNSPECIFIED ExecutionDriverKind = 0
	// HOST_PROCESS named the host-process driver, removed in issue #781. The
	// number stays reserved (the enum is NOT renumbered) to preserve wire
	// compatibility, but no Worker advertises it and no shipped driver maps to it.
	ExecutionDriverKind_EXECUTION_DRIVER_KIND_HOST_PROCESS ExecutionDriverKind = 1
	ExecutionDriverKind_EXECUTION_DRIVER_KIND_CONTAINER    ExecutionDriverKind = 2
)

// Enum value maps for ExecutionDriverKind.
var (
	ExecutionDriverKind_name = map[int32]string{
		0: "EXECUTION_DRIVER_KIND_UNSPECIFIED",
		1: "EXECUTION_DRIVER_KIND_HOST_PROCESS",
		2: "EXECUTION_DRIVER_KIND_CONTAINER",
	}
	ExecutionDriverKind_value = map[string]int32{
		"EXECUTION_DRIVER_KIND_UNSPECIFIED":  0,
		"EXECUTION_DRIVER_KIND_HOST_PROCESS": 1,
		"EXECUTION_DRIVER_KIND_CONTAINER":    2,
	}
)

func (x ExecutionDriverKind) Enum() *ExecutionDriverKind {
	p := new(ExecutionDriverKind)
	*p = x
	return p
}

func (x ExecutionDriverKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionDriverKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_controlplane_v1_control_plane_proto_enumTypes[0].Descriptor()
}

func (ExecutionDriverKind) Type() protoreflect.EnumType {
	return &file_mcsd_controlplane_v1_control_plane_proto_enumTypes[0]
}

func (x ExecutionDriverKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionDriverKind.Descriptor instead.
func (ExecutionDriverKind) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

// LaunchMode selects how the Worker launches a server's process (issue #305).
// It is additive: a Worker that does not understand a value falls back to the
// JAR launch its older code already implemented (UNSPECIFIED == JAR).
type LaunchMode int32

const (
	// Unspecified is treated as LAUNCH_MODE_JAR (backwards compatibility).
	LaunchMode_LAUNCH_MODE_UNSPECIFIED LaunchMode = 0
	// Jar runs `java -jar <jar_relpath> nogui` directly (vanilla, Paper, etc.).
	LaunchMode_LAUNCH_MODE_JAR LaunchMode = 1
	// ForgeArgsfile runs the Forge launch via its generated unix args file,
	// discovered under libraries/net/minecraftforge/forge/*/unix_args.txt in the
	// working set. When that args file is absent the working set is uninstalled,
	// so the Worker first runs `java -jar <jar_relpath> --installServer` as a
	// supervised phase of the start, then launches via the now-present args file.
	LaunchMode_LAUNCH_MODE_FORGE_ARGSFILE LaunchMode = 2
)

// Enum value maps for LaunchMode.
var (
	LaunchMode_name = map[int32]string{
		0: "LAUNCH_MODE_UNSPECIFIED",
		1: "LAUNCH_MODE_JAR",
		2: "LAUNCH_MODE_FORGE_ARGSFILE",
	}
	LaunchMode_value = map[string]int32{
		"LAUNCH_MODE_UNSPECIFIED":    0,
		"LAUNCH_MODE_JAR":            1,
		"LAUNCH_MODE_FORGE_ARGSFILE": 2,
	}
)

func (x LaunchMode) Enum() *LaunchMode {
	p := new(LaunchMode)
	*p = x
	return p
}

func (x LaunchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LaunchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_controlplane_v1_control_plane_proto_enumTypes[1].Descriptor()
}

func (LaunchMode) Type() protoreflect.EnumType {
	return &file_mcsd_controlplane_v1_control_plane_proto_enumTypes[1]
}

func (x LaunchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LaunchMode.Descriptor instead.
func (LaunchMode) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{1}
}

// FileAccessReason refines a FILE_ACCESS_DENIED failure (issue #548). The Worker
// emits FILE_ACCESS_DENIED for several conditions that are NOT path-syntax
// problems; this enum carries which one so the API maps each to an honest
// problem reason and HTTP status instead of a misleading "invalid path".
type FileAccessReason int32

const (
	// Unspecified is the default for a non-file failure and for a genuine path
	// denial (a traversal-unsafe path: absolute, a ".." component, or a
	// resolution refusal). The API maps it to 422 invalid_path, the historical
	// behaviour, so an older Worker that never sets this field is unchanged.
	FileAccessReason_FILE_ACCESS_REASON_UNSPECIFIED FileAccessReason = 0
	// The target path resolves to a directory where a file was required (a read or
	// an edit of a directory). The API maps it to 422 is_a_directory.
	FileAccessReason_FILE_ACCESS_REASON_IS_A_DIRECTORY FileAccessReason = 1
	// The target path resolves to a regular file where a directory was required (a
	// list of a file). The API maps it to 422 not_a_directory.
	FileAccessReason_FILE_ACCESS_REASON_NOT_A_DIRECTORY FileAccessReason = 2
	// The Worker refused to follow a symlink on the final or an intermediate path
	// component (the escape-vector defence, FR-FILE-4). The API maps it to 422
	// symlink_refused.
	FileAccessReason_FILE_ACCESS_REASON_SYMLINK_REFUSED FileAccessReason = 3
	// The read result or the edit payload exceeds the control-plane file cap. The
	// API maps it to 413 file_too_large.
	FileAccessReason_FILE_ACCESS_REASON_PAYLOAD_TOO_LARGE FileAccessReason = 4
)

// Enum value maps for FileAccessReason.
var (
	FileAccessReason_name = map[int32]string{
		0: "FILE_ACCESS_REASON_UNSPECIFIED",
		1: "FILE_ACCESS_REASON_IS_A_DIRECTORY",
		2: "FILE_ACCESS_REASON_NOT_A_DIRECTORY",
		3: "FILE_ACCESS_REASON_SYMLINK_REFUSED",
		4: "FILE_ACCESS_REASON_PAYLOAD_TOO_LARGE",
	}
	FileAccessReason_value = map[string]int32{
		"FILE_ACCESS_REASON_UNSPECIFIED":       0,
		"FILE_ACCESS_REASON_IS_A_DIRECTORY":    1,
		"FILE_ACCESS_REASON_NOT_A_DIRECTORY":   2,
		"FILE_ACCESS_REASON_SYMLINK_REFUSED":   3,
		"FILE_ACCESS_REASON_PAYLOAD_TOO_LARGE": 4,
	}
)

func (x FileAccessReason) Enum() *FileAccessReason {
	p := new(FileAccessReason)
	*p = x
	return p
}

func (x FileAccessReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileAccessReason) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_controlplane_v1_control_plane_proto_enumTypes[2].Descriptor()
}

func (FileAccessReason) Type() protoreflect.EnumType {
	return &file_mcsd_controlplane_v1_control_plane_proto_enumTypes[2]
}

func (x FileAccessReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileAccessReason.Descriptor instead.
func (FileAccessReason) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{2}
}

// CommandErrorCode classifies a command failure.
type CommandErrorCode int32

const (
	CommandErrorCode_COMMAND_ERROR_CODE_UNSPECIFIED CommandErrorCode = 0
	// The target server is not known to this Worker.
	CommandErrorCode_COMMAND_ERROR_CODE_SERVER_NOT_FOUND CommandErrorCode = 1
	// The command is invalid for the server's current state (e.g. start a
	// running server, RCON on a stopped one).
	CommandErrorCode_COMMAND_ERROR_CODE_INVALID_STATE CommandErrorCode = 2
	// The requested execution driver is not available on this Worker.
	CommandErrorCode_COMMAND_ERROR_CODE_DRIVER_UNAVAILABLE CommandErrorCode = 3
	// A file path was rejected (traversal / not found / not permitted).
	CommandErrorCode_COMMAND_ERROR_CODE_FILE_ACCESS_DENIED CommandErrorCode = 4
	// A hydrate/snapshot data-plane transfer failed.
	CommandErrorCode_COMMAND_ERROR_CODE_TRANSFER_FAILED CommandErrorCode = 5
	// The Worker failed to apply the command for an unclassified reason.
	CommandErrorCode_COMMAND_ERROR_CODE_INTERNAL CommandErrorCode = 6
	// A StartServer could not publish a host port because it is already in use
	// (e.g. two servers sharing server-port on one Worker). Sanitized from the
	// container driver's start error; the raw daemon text stays in Worker logs.
	CommandErrorCode_COMMAND_ERROR_CODE_PORT_CONFLICT CommandErrorCode = 7
	// A StartServer could not find or pull the container image for the server's
	// Minecraft/Java version. Sanitized from the container driver's create error;
	// the raw daemon text stays in Worker logs.
	CommandErrorCode_COMMAND_ERROR_CODE_IMAGE_MISSING CommandErrorCode = 8
	// Another mutating lifecycle command is already in flight for this server, so
	// the Worker refused this one without applying it (issue #824). Distinct from
	// INVALID_STATE: the id is RESERVED (a re-issued duplicate after a stream
	// reconnect, or a detached stop still confirming termination), not in a
	// settled state like "already running". The outcome of the in-flight command
	// is not yet known, so the API must NOT converge an observed state on it — it
	// keeps the assignment/intent and retries on a later reconcile tick.
	CommandErrorCode_COMMAND_ERROR_CODE_BUSY CommandErrorCode = 9
)

// Enum value maps for CommandErrorCode.
var (
	CommandErrorCode_name = map[int32]string{
		0: "COMMAND_ERROR_CODE_UNSPECIFIED",
		1: "COMMAND_ERROR_CODE_SERVER_NOT_FOUND",
		2: "COMMAND_ERROR_CODE_INVALID_STATE",
		3: "COMMAND_ERROR_CODE_DRIVER_UNAVAILABLE",
		4: "COMMAND_ERROR_CODE_FILE_ACCESS_DENIED",
		5: "COMMAND_ERROR_CODE_TRANSFER_FAILED",
		6: "COMMAND_ERROR_CODE_INTERNAL",
		7: "COMMAND_ERROR_CODE_PORT_CONFLICT",
		8: "COMMAND_ERROR_CODE_IMAGE_MISSING",
		9: "COMMAND_ERROR_CODE_BUSY",
	}
	CommandErrorCode_value = map[string]int32{
		"COMMAND_ERROR_CODE_UNSPECIFIED":        0,
		"COMMAND_ERROR_CODE_SERVER_NOT_FOUND":   1,
		"COMMAND_ERROR_CODE_INVALID_STATE":      2,
		"COMMAND_ERROR_CODE_DRIVER_UNAVAILABLE": 3,
		"COMMAND_ERROR_CODE_FILE_ACCESS_DENIED": 4,
		"COMMAND_ERROR_CODE_TRANSFER_FAILED":    5,
		"COMMAND_ERROR_CODE_INTERNAL":           6,
		"COMMAND_ERROR_CODE_PORT_CONFLICT":      7,
		"COMMAND_ERROR_CODE_IMAGE_MISSING":      8,
		"COMMAND_ERROR_CODE_BUSY":               9,
	}
)

func (x CommandErrorCode) Enum() *CommandErrorCode {
	p := new(CommandErrorCode)
	*p = x
	return p
}

func (x CommandErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_controlplane_v1_control_plane_proto_enumTypes[3].Descriptor()
}

func (CommandErrorCode) Type() protoreflect.EnumType {
	return &file_mcsd_controlplane_v1_control_plane_proto_enumTypes[3]
}

func (x CommandErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandErrorCode.Descriptor instead.
func (CommandErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{3}
}

// ServerState is the observed runtime state of a server (FR-SRV-4:
// running / stopped / starting / crashed, plus the in-between transitions and a
// restarting state the lifecycle commands produce). This is the full set of
// values a Worker can report. The API caches the last-reported value in
// Server.observed_state (DATABASE.md); that column also allows "unknown", which
// is an API-side inference (set when the owning Worker disconnects), never
// reported by a Worker, so it is intentionally not a value here.
type ServerState int32

const (
	ServerState_SERVER_STATE_UNSPECIFIED ServerState = 0
	ServerState_SERVER_STATE_STARTING    ServerState = 1
	ServerState_SERVER_STATE_RUNNING     ServerState = 2
	ServerState_SERVER_STATE_STOPPING    ServerState = 3
	ServerState_SERVER_STATE_STOPPED     ServerState = 4
	ServerState_SERVER_STATE_RESTARTING  ServerState = 5
	ServerState_SERVER_STATE_CRASHED     ServerState = 6
)

// Enum value maps for ServerState.
var (
	ServerState_name = map[int32]string{
		0: "SERVER_STATE_UNSPECIFIED",
		1: "SERVER_STATE_STARTING",
		2: "SERVER_STATE_RUNNING",
		3: "SERVER_STATE_STOPPING",
		4: "SERVER_STATE_STOPPED",
		5: "SERVER_STATE_RESTARTING",
		6: "SERVER_STATE_CRASHED",
	}
	ServerState_value = map[string]int32{
		"SERVER_STATE_UNSPECIFIED": 0,
		"SERVER_STATE_STARTING":    1,
		"SERVER_STATE_RUNNING":     2,
		"SERVER_STATE_STOPPING":    3,
		"SERVER_STATE_STOPPED":     4,
		"SERVER_STATE_RESTARTING":  5,
		"SERVER_STATE_CRASHED":     6,
	}
)

func (x ServerState) Enum() *ServerState {
	p := new(ServerState)
	*p = x
	return p
}

func (x ServerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerState) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_controlplane_v1_control_plane_proto_enumTypes[4].Descriptor()
}

func (ServerState) Type() protoreflect.EnumType {
	return &file_mcsd_controlplane_v1_control_plane_proto_enumTypes[4]
}

func (x ServerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerState.Descriptor instead.
func (ServerState) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{4}
}

// LogStream identifies which output stream a LogLine came from.
type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_controlplane_v1_control_plane_proto_enumTypes[5].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_mcsd_controlplane_v1_control_plane_proto_enumTypes[5]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{5}
}

// WorkerMessage is every message a Worker sends to the API over the stream.
// Exactly one payload field is set.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// correlation_id ties a flow together end to end (REQUIREMENTS.md NFR-OBS-1).
	// For a command_result it MUST equal the originating ApiCommand.command_id so
	// the API can match a result to its command. For unsolicited events it is a
	// fresh id the API can log and trace.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// emitted_at is the Worker's clock reading when the message was produced.
	EmittedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_CommandResult
	//	*WorkerMessage_Event
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *WorkerMessage) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	// Register MUST be the first message on a fresh stream (FR-WRK-1).
	Register *Register `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

type WorkerMessage_CommandResult struct {
	// CommandResult answers an ApiCommand (success or error).
	CommandResult *CommandResult `protobuf:"bytes,4,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type WorkerMessage_Event struct {
	// Event is an asynchronous status / log / metrics / heartbeat report.
	Event *Event `protobuf:"bytes,5,opt,name=event,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_CommandResult) isWorkerMessage_Payload() {}

func (*WorkerMessage_Event) isWorkerMessage_Payload() {}

// ApiMessage is every message the API sends to a Worker over the stream.
// Exactly one payload field is set.
type ApiMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// correlation_id traces the flow (REQUIREMENTS.md NFR-OBS-1). For a command it
	// is the same value as the command's command_id; for register_ack it echoes
	// the Register message's correlation_id.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// sent_at is the API's clock reading when the message was produced.
	SentAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiMessage_RegisterAck
	//	*ApiMessage_ApiCommand
	Payload       isApiMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiMessage) Reset() {
	*x = ApiMessage{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiMessage) ProtoMessage() {}

func (x *ApiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiMessage.ProtoReflect.Descriptor instead.
func (*ApiMessage) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *ApiMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ApiMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ApiMessage) GetPayload() isApiMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ApiMessage) GetApiCommand() *ApiCommand {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_ApiCommand); ok {
			return x.ApiCommand
		}
	}
	return nil
}

type isApiMessage_Payload interface {
	isApiMessage_Payload()
}

type ApiMessage_RegisterAck struct {
	// RegisterAck accepts or rejects a Register (sent first, in response).
	RegisterAck *RegisterAck `protobuf:"bytes,3,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ApiMessage_ApiCommand struct {
	// ApiCommand instructs the Worker to act on a server.
	ApiCommand *ApiCommand `protobuf:"bytes,4,opt,name=api_command,json=apiCommand,proto3,oneof"`
}

func (*ApiMessage_RegisterAck) isApiMessage_Payload() {}

func (*ApiMessage_ApiCommand) isApiMessage_Payload() {}

// Register is the Worker's opening message: who it is and what it can run.
type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// worker_id is the stable identifier the Worker registers under
	// (CONFIGURATION.md Section 6.1 worker.id).
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// worker_version is the Worker build/release string, for fleet visibility.
	WorkerVersion string `protobuf:"bytes,2,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	// capabilities advertises the drivers and resources the API's greedy
	// placement filters on (FR-WRK-3).
	Capabilities *WorkerCapabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// held_servers advertises the working sets the Worker already holds in its
	// persistent local scratch at registration, each tagged with the GENERATION the
	// local working set is at (issue #763). The API uses this to skip the
	// destructive hydrate on a same-worker restart — hydrating would unpack the last
	// authoritative snapshot over the Worker's LIVE, newer working set and roll the
	// world back — but ONLY when the held generation is fresh enough: the reconciler
	// hydrates whenever the held generation is older than the authoritative store
	// generation (presence at a stale generation, e.g. an A->B->A leftover scratch,
	// is NOT fresh enough). This generalizes the presence-only skip of issue #696,
	// which was correct only because the one A->B->A path always re-placed through a
	// hydrate; carrying the generation keeps it correct under any future flow.
	//
	// This REPLACES the prior `repeated string held_server_ids` (issue #696): a wire
	// break, justified because api/ and worker/ ship together (CONTRIBUTING.md) and a
	// clean replacement is simpler than a parallel field. An older Worker that does
	// not set held_servers reports holding nothing, so the API hydrates as before —
	// never silently booting a fresh/empty world.
	HeldServers   []*HeldServer `protobuf:"bytes,4,rep,name=held_servers,json=heldServers,proto3" json:"held_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Register) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

func (x *Register) GetCapabilities() *WorkerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Register) GetHeldServers() []*HeldServer {
	if x != nil {
		return x.HeldServers
	}
	return nil
}

// HeldServer is one working set the Worker holds in local scratch, with the
// generation it is at (issue #763). The generation is the authoritative store
// generation the working set was last hydrated from or last snapshotted to: it is
// stamped by the API data plane on each transfer and persisted by the Worker
// alongside the scratch, so a same-worker restart re-reports it and a scratch GC
// (issue #762) drops it. generation 0 means "held but at an unknown generation"
// (e.g. a scratch that predates this field): the API treats 0 as older than any
// published store generation and hydrates.
type HeldServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id is the API's identifier for the held server.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// generation is the working-set generation in the Worker's scratch.
	Generation    uint64 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeldServer) Reset() {
	*x = HeldServer{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeldServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeldServer) ProtoMessage() {}

func (x *HeldServer) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeldServer.ProtoReflect.Descriptor instead.
func (*HeldServer) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *HeldServer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HeldServer) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// WorkerCapabilities is what a Worker advertises at registration (FR-WRK-1).
type WorkerCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// drivers is the set of execution backends this Worker offers
	// (CONFIGURATION.md Section 6.2 worker.drivers).
	Drivers []ExecutionDriverKind `protobuf:"varint,1,rep,packed,name=drivers,proto3,enum=mcsd.controlplane.v1.ExecutionDriverKind" json:"drivers,omitempty"`
	// max_servers is the Worker's free-capacity hint for placement; 0 means "no
	// advertised cap" (CONFIGURATION.md Section 6.2 worker.max_servers).
	MaxServers uint32 `protobuf:"varint,2,opt,name=max_servers,json=maxServers,proto3" json:"max_servers,omitempty"`
	// resources advertises host resources for placement and monitoring.
	Resources     *HostResources `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCapabilities) Reset() {
	*x = WorkerCapabilities{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapabilities) ProtoMessage() {}

func (x *WorkerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapabilities.ProtoReflect.Descriptor instead.
func (*WorkerCapabilities) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerCapabilities) GetDrivers() []ExecutionDriverKind {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *WorkerCapabilities) GetMaxServers() uint32 {
	if x != nil {
		return x.MaxServers
	}
	return 0
}

func (x *WorkerCapabilities) GetResources() *HostResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

// HostResources is a coarse description of a Worker host's resources.
type HostResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_cores is the number of logical CPUs available to the Worker.
	CpuCores uint32 `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// memory_bytes is the total memory available to the Worker.
	MemoryBytes   uint64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostResources) Reset() {
	*x = HostResources{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostResources) ProtoMessage() {}

func (x *HostResources) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostResources.ProtoReflect.Descriptor instead.
func (*HostResources) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *HostResources) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostResources) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// RegisterAck accepts or rejects a registration.
type RegisterAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is true when the API admitted this Worker into the registry.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// heartbeat_interval is how often the API expects a HEARTBEAT event. The API
	// marks the Worker disconnected after it misses heartbeats past its liveness
	// window (CONFIGURATION.md Section 5.1 control.heartbeat_timeout_seconds,
	// FR-WRK-2).
	HeartbeatInterval *durationpb.Duration `protobuf:"bytes,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// rejection_reason explains a refusal (e.g. bad credential, duplicate id);
	// empty when accepted is true.
	RejectionReason string `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// transfer_deadline bounds a single data-plane transfer (the snapshot upload
	// and the hydrate download) Worker-side. The API derives it from its own
	// hydrate/snapshot budgets plus a small margin, so it is always >= the API
	// budget: the API-side timeout fires first and this Worker bound is the
	// cleanup backstop that structurally closes the unbounded-upload case (an
	// upload outliving snapshot_timeout_seconds indefinitely, #874/#869). The
	// Worker applies it as a per-transfer context deadline; a non-positive or
	// unset value (an older API) leaves the transfer unbounded as before.
	TransferDeadline *durationpb.Duration `protobuf:"bytes,4,opt,name=transfer_deadline,json=transferDeadline,proto3" json:"transfer_deadline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *RegisterAck) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *RegisterAck) GetTransferDeadline() *durationpb.Duration {
	if x != nil {
		return x.TransferDeadline
	}
	return nil
}

// ApiCommand is one instruction the Worker must act on and answer with a
// CommandResult carrying the same command_id.
type ApiCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command_id correlates this command with its CommandResult
	// (REQUIREMENTS.md NFR-OBS-1).
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// server_id is the API's identifier for the target server. Set for every
	// per-server command; empty only for future fleet-wide commands.
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ApiCommand_Start
	//	*ApiCommand_Stop
	//	*ApiCommand_Restart
	//	*ApiCommand_ServerCommand
	//	*ApiCommand_Hydrate
	//	*ApiCommand_Snapshot
	//	*ApiCommand_ReadFile
	//	*ApiCommand_EditFile
	//	*ApiCommand_ListFiles
	//	*ApiCommand_TunnelDial
	Command       isApiCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiCommand) Reset() {
	*x = ApiCommand{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiCommand) ProtoMessage() {}

func (x *ApiCommand) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiCommand.ProtoReflect.Descriptor instead.
func (*ApiCommand) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *ApiCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ApiCommand) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ApiCommand) GetCommand() isApiCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ApiCommand) GetStart() *StartServer {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ApiCommand) GetStop() *StopServer {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ApiCommand) GetRestart() *RestartServer {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ApiCommand) GetServerCommand() *ServerCommand {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_ServerCommand); ok {
			return x.ServerCommand
		}
	}
	return nil
}

func (x *ApiCommand) GetHydrate() *HydrateTrigger {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_Hydrate); ok {
			return x.Hydrate
		}
	}
	return nil
}

func (x *ApiCommand) GetSnapshot() *SnapshotTrigger {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ApiCommand) GetReadFile() *ReadFile {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *ApiCommand) GetEditFile() *EditFile {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_EditFile); ok {
			return x.EditFile
		}
	}
	return nil
}

func (x *ApiCommand) GetListFiles() *ListFiles {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_ListFiles); ok {
			return x.ListFiles
		}
	}
	return nil
}

func (x *ApiCommand) GetTunnelDial() *TunnelDial {
	if x != nil {
		if x, ok := x.Command.(*ApiCommand_TunnelDial); ok {
			return x.TunnelDial
		}
	}
	return nil
}

type isApiCommand_Command interface {
	isApiCommand_Command()
}

type ApiCommand_Start struct {
	Start *StartServer `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type ApiCommand_Stop struct {
	Stop *StopServer `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type ApiCommand_Restart struct {
	Restart *RestartServer `protobuf:"bytes,5,opt,name=restart,proto3,oneof"`
}

type ApiCommand_ServerCommand struct {
	// ServerCommand forwards an RCON / console command (FR-SRV-5).
	ServerCommand *ServerCommand `protobuf:"bytes,6,opt,name=server_command,json=serverCommand,proto3,oneof"`
}

type ApiCommand_Hydrate struct {
	// Hydrate triggers the Worker to pull the working set from the API data
	// plane before launch (FR-DATA-4). The bulk transfer itself rides the HTTP
	// data plane, not this stream (Section 5.1).
	Hydrate *HydrateTrigger `protobuf:"bytes,7,opt,name=hydrate,proto3,oneof"`
}

type ApiCommand_Snapshot struct {
	// Snapshot triggers the Worker to push its working set back to the API data
	// plane (FR-DATA-4, FR-DATA-7).
	Snapshot *SnapshotTrigger `protobuf:"bytes,8,opt,name=snapshot,proto3,oneof"`
}

type ApiCommand_ReadFile struct {
	// ReadFile reads from a running server's live working set (Section 7.2).
	ReadFile *ReadFile `protobuf:"bytes,9,opt,name=read_file,json=readFile,proto3,oneof"`
}

type ApiCommand_EditFile struct {
	// EditFile writes to a running server's live working set (Section 7.2).
	EditFile *EditFile `protobuf:"bytes,10,opt,name=edit_file,json=editFile,proto3,oneof"`
}

type ApiCommand_ListFiles struct {
	// ListFiles browses a directory in a running server's live working set
	// (Section 6.9, Section 7.2).
	ListFiles *ListFiles `protobuf:"bytes,11,opt,name=list_files,json=listFiles,proto3,oneof"`
}

type ApiCommand_TunnelDial struct {
	// TunnelDial instructs the Worker to open a dial-back tunnel to the relay
	// for one player session (RELAY.md Section 5). Bypasses the slow-lane
	// concurrency cap (like ServerCommand) so a join does not queue behind a
	// hydrate.
	TunnelDial *TunnelDial `protobuf:"bytes,12,opt,name=tunnel_dial,json=tunnelDial,proto3,oneof"`
}

func (*ApiCommand_Start) isApiCommand_Command() {}

func (*ApiCommand_Stop) isApiCommand_Command() {}

func (*ApiCommand_Restart) isApiCommand_Command() {}

func (*ApiCommand_ServerCommand) isApiCommand_Command() {}

func (*ApiCommand_Hydrate) isApiCommand_Command() {}

func (*ApiCommand_Snapshot) isApiCommand_Command() {}

func (*ApiCommand_ReadFile) isApiCommand_Command() {}

func (*ApiCommand_EditFile) isApiCommand_Command() {}

func (*ApiCommand_ListFiles) isApiCommand_Command() {}

func (*ApiCommand_TunnelDial) isApiCommand_Command() {}

// StartServer launches a server on the Worker. Hydrate (FR-DATA-4) precedes the
// launch; the API issues a HydrateTrigger first, then StartServer.
type StartServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// driver is the execution backend to use; it MUST be one the Worker
	// advertised (FR-EXE-3 fixes it per server).
	Driver ExecutionDriverKind `protobuf:"varint,1,opt,name=driver,proto3,enum=mcsd.controlplane.v1.ExecutionDriverKind" json:"driver,omitempty"`
	// jar_relpath is the server JAR path inside the hydrated working set. The API
	// owns JAR retrieval and ships it via hydrate; the Worker never fetches it
	// (ARCHITECTURE.md Section 7.3).
	JarRelpath string `protobuf:"bytes,2,opt,name=jar_relpath,json=jarRelpath,proto3" json:"jar_relpath,omitempty"`
	// minecraft_version lets the Worker pick the Java runtime (FR-EXE-5); the API
	// does not choose the java binary.
	MinecraftVersion string `protobuf:"bytes,3,opt,name=minecraft_version,json=minecraftVersion,proto3" json:"minecraft_version,omitempty"`
	// launch_mode selects how the Worker launches the server (a vanilla/Paper JAR
	// launch vs a Forge args-file launch with a supervised installer step). It is
	// carried explicitly on the command, never inferred from the working-set
	// contents. LAUNCH_MODE_UNSPECIFIED is treated as LAUNCH_MODE_JAR for
	// backwards compatibility: a Worker launching it behaves exactly as it did
	// before this field existed (a `java -jar <jar> nogui` launch).
	LaunchMode LaunchMode `protobuf:"varint,4,opt,name=launch_mode,json=launchMode,proto3,enum=mcsd.controlplane.v1.LaunchMode" json:"launch_mode,omitempty"`
	// memory_limit_bytes is the per-server memory ceiling (the container/process
	// limit) the operator declared on the server config (issue #706, epic #704).
	// It carries operator intent — the LIMIT, not a pre-computed JVM flag — and
	// the Worker derives the JVM heap (`-Xmx = limit − headroom`) from it. 0/unset
	// means "the driver picks a default" (the JVM default heap, today's behavior),
	// so a command from an API that does not set the field is unchanged. Driver
	// enforcement of the ceiling (Docker `Memory`, host limits) is later sub-issues
	// (#707/#708) and not implied by this field alone.
	MemoryLimitBytes uint64 `protobuf:"varint,5,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// cpu_millis is the per-server CPU allocation in millicores (1000 = one core)
	// the operator declared on the server config (issue #723, epic #704). It is a
	// SOFT, relative allocation (owner decision 2026-06-09), not a hard quota: the
	// Worker carries it as-is — there is NO derivation step (unlike the JVM heap
	// from memory_limit_bytes) — and the enforcement driver (#724) turns it into a
	// relative CPUShares weight. 0/unset means "no per-server allocation → the
	// driver's default weight", so a command from an API that does not set the
	// field is unchanged.
	CpuMillis     uint32 `protobuf:"varint,6,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServer) Reset() {
	*x = StartServer{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServer) ProtoMessage() {}

func (x *StartServer) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServer.ProtoReflect.Descriptor instead.
func (*StartServer) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *StartServer) GetDriver() ExecutionDriverKind {
	if x != nil {
		return x.Driver
	}
	return ExecutionDriverKind_EXECUTION_DRIVER_KIND_UNSPECIFIED
}

func (x *StartServer) GetJarRelpath() string {
	if x != nil {
		return x.JarRelpath
	}
	return ""
}

func (x *StartServer) GetMinecraftVersion() string {
	if x != nil {
		return x.MinecraftVersion
	}
	return ""
}

func (x *StartServer) GetLaunchMode() LaunchMode {
	if x != nil {
		return x.LaunchMode
	}
	return LaunchMode_LAUNCH_MODE_UNSPECIFIED
}

func (x *StartServer) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *StartServer) GetCpuMillis() uint32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

// StopServer stops a running server. A graceful stop takes an event-driven
// snapshot before exit (FR-DATA-7); set force to skip the graceful path.
type StopServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServer) Reset() {
	*x = StopServer{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServer) ProtoMessage() {}

func (x *StopServer) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServer.ProtoReflect.Descriptor instead.
func (*StopServer) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *StopServer) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// RestartServer stops then starts the server in place.
type RestartServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServer) Reset() {
	*x = RestartServer{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServer) ProtoMessage() {}

func (x *RestartServer) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServer.ProtoReflect.Descriptor instead.
func (*RestartServer) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{10}
}

// ServerCommand forwards a console / RCON command to the running server
// (FR-SRV-5). The output is returned in the CommandResult.
type ServerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// line is the raw command line sent to the server console (e.g. "say hi").
	Line          string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *ServerCommand) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// HydrateTrigger tells the Worker to pull a server's working set from the API
// data plane into local scratch (FR-DATA-4). transfer_url and transfer_token
// address the API-terminated HTTP data-plane endpoint (Section 5.1); the bulk
// bytes never traverse this stream.
type HydrateTrigger struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TransferUrl string                 `protobuf:"bytes,1,opt,name=transfer_url,json=transferUrl,proto3" json:"transfer_url,omitempty"`
	// transfer_token is a short-lived credential authorizing this one transfer.
	TransferToken string `protobuf:"bytes,2,opt,name=transfer_token,json=transferToken,proto3" json:"transfer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HydrateTrigger) Reset() {
	*x = HydrateTrigger{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HydrateTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HydrateTrigger) ProtoMessage() {}

func (x *HydrateTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HydrateTrigger.ProtoReflect.Descriptor instead.
func (*HydrateTrigger) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *HydrateTrigger) GetTransferUrl() string {
	if x != nil {
		return x.TransferUrl
	}
	return ""
}

func (x *HydrateTrigger) GetTransferToken() string {
	if x != nil {
		return x.TransferToken
	}
	return ""
}

// SnapshotTrigger tells the Worker to push its working set back to the API data
// plane (FR-DATA-4, FR-DATA-7). For a running server the Worker performs
// save-all over RCON first (Section 6.9).
type SnapshotTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferUrl   string                 `protobuf:"bytes,1,opt,name=transfer_url,json=transferUrl,proto3" json:"transfer_url,omitempty"`
	TransferToken string                 `protobuf:"bytes,2,opt,name=transfer_token,json=transferToken,proto3" json:"transfer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotTrigger) Reset() {
	*x = SnapshotTrigger{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotTrigger) ProtoMessage() {}

func (x *SnapshotTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotTrigger.ProtoReflect.Descriptor instead.
func (*SnapshotTrigger) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotTrigger) GetTransferUrl() string {
	if x != nil {
		return x.TransferUrl
	}
	return ""
}

func (x *SnapshotTrigger) GetTransferToken() string {
	if x != nil {
		return x.TransferToken
	}
	return ""
}

// ReadFile reads a path from a running server's live working set (Section 7.2).
// Path-traversal protection is enforced on the Worker side (FR-FILE-4).
type ReadFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is relative to the server's working-set root.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFile) Reset() {
	*x = ReadFile{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFile) ProtoMessage() {}

func (x *ReadFile) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFile.ProtoReflect.Descriptor instead.
func (*ReadFile) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *ReadFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// EditFile writes content to a path in a running server's live working set
// (Section 7.2). Path-traversal protection is enforced on the Worker side
// (FR-FILE-4).
type EditFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditFile) Reset() {
	*x = EditFile{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFile) ProtoMessage() {}

func (x *EditFile) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFile.ProtoReflect.Descriptor instead.
func (*EditFile) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *EditFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EditFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// ListFiles lists the entries of a directory in a running server's live working
// set (Section 6.9, Section 7.2). The listing comes back in the CommandResult's
// file_listing. Path-traversal protection is enforced on the Worker side
// (FR-FILE-4); the listing is read-only.
type ListFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the directory relative to the server's working-set root; "." (or
	// empty) lists the root itself.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFiles) Reset() {
	*x = ListFiles{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFiles) ProtoMessage() {}

func (x *ListFiles) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFiles.ProtoReflect.Descriptor instead.
func (*ListFiles) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *ListFiles) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// TunnelDial instructs the Worker to dial back the relay's tunnel listener for
// one player session (RELAY.md Section 5). Everything the Worker needs arrives
// in-band so it requires zero new configuration. Bypasses the slow-lane
// concurrency cap (like ServerCommand) — a join must not queue behind a hydrate.
type TunnelDial struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id identifies the local server whose game port the Worker splices
	// to. The Worker resolves it to the running instance's published loopback
	// game port; if the server is not running locally it returns a
	// CommandResult error. RELAY.md Section 5.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// endpoint is the relay tunnel endpoint to dial, in host:port form. Taken
	// from the relay's Register call so the API is the single config source.
	// RELAY.md Section 5.
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// token is the single-use session token the Worker presents to the relay
	// after the TLS handshake. The relay matches it to the waiting player
	// connection and then starts the splice. RELAY.md Section 5.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// tls_ca_pem is the optional PEM-encoded CA bundle the Worker uses to
	// verify the relay's tunnel certificate. Empty means system roots (public
	// CA). Delivered in-band so the Worker needs zero new configuration.
	// RELAY.md Section 5.
	TlsCaPem      string `protobuf:"bytes,4,opt,name=tls_ca_pem,json=tlsCaPem,proto3" json:"tls_ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelDial) Reset() {
	*x = TunnelDial{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelDial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelDial) ProtoMessage() {}

func (x *TunnelDial) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelDial.ProtoReflect.Descriptor instead.
func (*TunnelDial) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *TunnelDial) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *TunnelDial) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TunnelDial) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TunnelDial) GetTlsCaPem() string {
	if x != nil {
		return x.TlsCaPem
	}
	return ""
}

// CommandResult answers exactly one ApiCommand. The enclosing WorkerMessage's
// correlation_id equals the command's command_id.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success is true when the command was applied without error.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error describes the failure; absent when success is true.
	Error *CommandError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// result carries command-specific output, when the command produces any.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResult_CommandOutput
	//	*CommandResult_FileContent
	//	*CommandResult_FileListing
	Result        isCommandResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetError() *CommandError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CommandResult) GetResult() isCommandResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResult) GetCommandOutput() string {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return ""
}

func (x *CommandResult) GetFileContent() []byte {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_FileContent); ok {
			return x.FileContent
		}
	}
	return nil
}

func (x *CommandResult) GetFileListing() *FileListing {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_FileListing); ok {
			return x.FileListing
		}
	}
	return nil
}

type isCommandResult_Result interface {
	isCommandResult_Result()
}

type CommandResult_CommandOutput struct {
	// command_output is the console/RCON output for a ServerCommand.
	CommandOutput string `protobuf:"bytes,3,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type CommandResult_FileContent struct {
	// file_content is the bytes read for a ReadFile.
	FileContent []byte `protobuf:"bytes,4,opt,name=file_content,json=fileContent,proto3,oneof"`
}

type CommandResult_FileListing struct {
	// file_listing is the directory listing for a ListFiles.
	FileListing *FileListing `protobuf:"bytes,5,opt,name=file_listing,json=fileListing,proto3,oneof"`
}

func (*CommandResult_CommandOutput) isCommandResult_Result() {}

func (*CommandResult_FileContent) isCommandResult_Result() {}

func (*CommandResult_FileListing) isCommandResult_Result() {}

// FileListing is the directory listing returned for a ListFiles command. Entries
// are unordered; the API sorts for display.
type FileListing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries are the directory's immediate children (not recursive).
	Entries []*FileEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// truncated is true when the directory held more than the Worker's per-listing
	// cap and entries was clipped to that cap. The browse view shows a partial
	// listing rather than refusing an enormous directory.
	Truncated     bool `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListing) Reset() {
	*x = FileListing{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListing) ProtoMessage() {}

func (x *FileListing) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListing.ProtoReflect.Descriptor instead.
func (*FileListing) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{19}
}

func (x *FileListing) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FileListing) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// FileEntry is one child of a listed directory. The shape mirrors the API's
// authoritative-Storage listing (name, is_dir, size) so a running-server listing
// and an at-rest listing unify into one response shape.
type FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the entry's base name (no path separators).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// is_dir is true for a subdirectory, false for a regular file.
	IsDir bool `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// size is the file size in bytes; 0 for a directory.
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{20}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CommandError reports why a command failed (NFR-OBS-1 error reporting).
type CommandError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code classifies the failure for programmatic handling.
	Code CommandErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=mcsd.controlplane.v1.CommandErrorCode" json:"code,omitempty"`
	// message is a human-readable explanation for logs and operators.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// file_access_reason refines a FILE_ACCESS_DENIED failure into the specific
	// condition the Worker hit (is-a-directory, symlink refusal, oversized
	// payload, etc.) so the API can surface an honest problem reason rather than
	// collapsing every file denial into "invalid path" (issue #548). It is only
	// meaningful when code is COMMAND_ERROR_CODE_FILE_ACCESS_DENIED; for every
	// other code it is UNSPECIFIED. The field is additive: an older Worker that
	// leaves it UNSPECIFIED, and a genuine traversal/path denial, both map back to
	// the pre-existing invalid-path behaviour.
	FileAccessReason FileAccessReason `protobuf:"varint,3,opt,name=file_access_reason,json=fileAccessReason,proto3,enum=mcsd.controlplane.v1.FileAccessReason" json:"file_access_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandError) Reset() {
	*x = CommandError{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandError) ProtoMessage() {}

func (x *CommandError) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandError.ProtoReflect.Descriptor instead.
func (*CommandError) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{21}
}

func (x *CommandError) GetCode() CommandErrorCode {
	if x != nil {
		return x.Code
	}
	return CommandErrorCode_COMMAND_ERROR_CODE_UNSPECIFIED
}

func (x *CommandError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandError) GetFileAccessReason() FileAccessReason {
	if x != nil {
		return x.FileAccessReason
	}
	return FileAccessReason_FILE_ACCESS_REASON_UNSPECIFIED
}

// Event is an asynchronous report from a Worker, not tied to a command.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id scopes the event to a server; empty for Worker-wide events such
	// as a heartbeat.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_StatusChange
	//	*Event_LogLine
	//	*Event_Metrics
	//	*Event_Heartbeat
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{22}
}

func (x *Event) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetStatusChange() *StatusChange {
	if x != nil {
		if x, ok := x.Event.(*Event_StatusChange); ok {
			return x.StatusChange
		}
	}
	return nil
}

func (x *Event) GetLogLine() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*Event_LogLine); ok {
			return x.LogLine
		}
	}
	return nil
}

func (x *Event) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Event.(*Event_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Event) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*Event_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_StatusChange struct {
	// StatusChange reports an observed server-state transition (FR-SRV-4,
	// FR-MON-1).
	StatusChange *StatusChange `protobuf:"bytes,2,opt,name=status_change,json=statusChange,proto3,oneof"`
}

type Event_LogLine struct {
	// LogLine streams a line of server output (FR-MON-2).
	LogLine *LogLine `protobuf:"bytes,3,opt,name=log_line,json=logLine,proto3,oneof"`
}

type Event_Metrics struct {
	// Metrics reports basic runtime metrics (FR-MON-3).
	Metrics *Metrics `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type Event_Heartbeat struct {
	// Heartbeat is the liveness signal (FR-WRK-2).
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*Event_StatusChange) isEvent_Event() {}

func (*Event_LogLine) isEvent_Event() {}

func (*Event_Metrics) isEvent_Event() {}

func (*Event_Heartbeat) isEvent_Event() {}

// StatusChange reports the Worker's observed runtime state for a server
// (FR-SRV-4). The API holds desired state; this is the observed side.
type StatusChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State ServerState            `protobuf:"varint,1,opt,name=state,proto3,enum=mcsd.controlplane.v1.ServerState" json:"state,omitempty"`
	// detail optionally explains the transition (e.g. a crash reason).
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusChange) Reset() {
	*x = StatusChange{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusChange) ProtoMessage() {}

func (x *StatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusChange.ProtoReflect.Descriptor instead.
func (*StatusChange) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{23}
}

func (x *StatusChange) GetState() ServerState {
	if x != nil {
		return x.State
	}
	return ServerState_SERVER_STATE_UNSPECIFIED
}

func (x *StatusChange) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// LogLine is a single line of a server's console output (FR-MON-2).
type LogLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// line is the raw log text without a trailing newline.
	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	// stream distinguishes stdout from stderr.
	Stream        LogStream `protobuf:"varint,2,opt,name=stream,proto3,enum=mcsd.controlplane.v1.LogStream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{24}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

// Metrics is a basic runtime metrics sample for a server (FR-MON-3). Fields are
// best-effort; a Worker that cannot measure one leaves it zero.
type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_millis is CPU usage in thousandths of a core (1000 == one full core).
	CpuMillis uint32 `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	// memory_bytes is the resident memory of the server process.
	MemoryBytes uint64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// player_count is the number of connected players, when known.
	PlayerCount   uint32 `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{25}
}

func (x *Metrics) GetCpuMillis() uint32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *Metrics) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Metrics) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

// Heartbeat is the periodic liveness signal (FR-WRK-2). Its cadence is the
// heartbeat_interval the API returned in RegisterAck.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_controlplane_v1_control_plane_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP(), []int{26}
}

var File_mcsd_controlplane_v1_control_plane_proto protoreflect.FileDescriptor

const file_mcsd_controlplane_v1_control_plane_proto_rawDesc = "" +
	"\n" +
	"(mcsd/controlplane/v1/control_plane.proto\x12\x14mcsd.controlplane.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\rWorkerMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x129\n" +
	"\n" +
	"emitted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12<\n" +
	"\bregister\x18\x03 \x01(\v2\x1e.mcsd.controlplane.v1.RegisterH\x00R\bregister\x12L\n" +
	"\x0ecommand_result\x18\x04 \x01(\v2#.mcsd.controlplane.v1.CommandResultH\x00R\rcommandResult\x123\n" +
	"\x05event\x18\x05 \x01(\v2\x1b.mcsd.controlplane.v1.EventH\x00R\x05eventB\t\n" +
	"\apayload\"\x80\x02\n" +
	"\n" +
	"ApiMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12F\n" +
	"\fregister_ack\x18\x03 \x01(\v2!.mcsd.controlplane.v1.RegisterAckH\x00R\vregisterAck\x12C\n" +
	"\vapi_command\x18\x04 \x01(\v2 .mcsd.controlplane.v1.ApiCommandH\x00R\n" +
	"apiCommandB\t\n" +
	"\apayload\"\xe1\x01\n" +
	"\bRegister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0eworker_version\x18\x02 \x01(\tR\rworkerVersion\x12L\n" +
	"\fcapabilities\x18\x03 \x01(\v2(.mcsd.controlplane.v1.WorkerCapabilitiesR\fcapabilities\x12C\n" +
	"\fheld_servers\x18\x04 \x03(\v2 .mcsd.controlplane.v1.HeldServerR\vheldServers\"I\n" +
	"\n" +
	"HeldServer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\"\xbd\x01\n" +
	"\x12WorkerCapabilities\x12C\n" +
	"\adrivers\x18\x01 \x03(\x0e2).mcsd.controlplane.v1.ExecutionDriverKindR\adrivers\x12\x1f\n" +
	"\vmax_servers\x18\x02 \x01(\rR\n" +
	"maxServers\x12A\n" +
	"\tresources\x18\x03 \x01(\v2#.mcsd.controlplane.v1.HostResourcesR\tresources\"O\n" +
	"\rHostResources\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\rR\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\"\xe6\x01\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12H\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReason\x12F\n" +
	"\x11transfer_deadline\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x10transferDeadline\"\xe1\x05\n" +
	"\n" +
	"ApiCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x129\n" +
	"\x05start\x18\x03 \x01(\v2!.mcsd.controlplane.v1.StartServerH\x00R\x05start\x126\n" +
	"\x04stop\x18\x04 \x01(\v2 .mcsd.controlplane.v1.StopServerH\x00R\x04stop\x12?\n" +
	"\arestart\x18\x05 \x01(\v2#.mcsd.controlplane.v1.RestartServerH\x00R\arestart\x12L\n" +
	"\x0eserver_command\x18\x06 \x01(\v2#.mcsd.controlplane.v1.ServerCommandH\x00R\rserverCommand\x12@\n" +
	"\ahydrate\x18\a \x01(\v2$.mcsd.controlplane.v1.HydrateTriggerH\x00R\ahydrate\x12C\n" +
	"\bsnapshot\x18\b \x01(\v2%.mcsd.controlplane.v1.SnapshotTriggerH\x00R\bsnapshot\x12=\n" +
	"\tread_file\x18\t \x01(\v2\x1e.mcsd.controlplane.v1.ReadFileH\x00R\breadFile\x12=\n" +
	"\tedit_file\x18\n" +
	" \x01(\v2\x1e.mcsd.controlplane.v1.EditFileH\x00R\beditFile\x12@\n" +
	"\n" +
	"list_files\x18\v \x01(\v2\x1f.mcsd.controlplane.v1.ListFilesH\x00R\tlistFiles\x12C\n" +
	"\vtunnel_dial\x18\f \x01(\v2 .mcsd.controlplane.v1.TunnelDialH\x00R\n" +
	"tunnelDialB\t\n" +
	"\acommand\"\xae\x02\n" +
	"\vStartServer\x12A\n" +
	"\x06driver\x18\x01 \x01(\x0e2).mcsd.controlplane.v1.ExecutionDriverKindR\x06driver\x12\x1f\n" +
	"\vjar_relpath\x18\x02 \x01(\tR\n" +
	"jarRelpath\x12+\n" +
	"\x11minecraft_version\x18\x03 \x01(\tR\x10minecraftVersion\x12A\n" +
	"\vlaunch_mode\x18\x04 \x01(\x0e2 .mcsd.controlplane.v1.LaunchModeR\n" +
	"launchMode\x12,\n" +
	"\x12memory_limit_bytes\x18\x05 \x01(\x04R\x10memoryLimitBytes\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x06 \x01(\rR\tcpuMillis\"\"\n" +
	"\n" +
	"StopServer\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\x0f\n" +
	"\rRestartServer\"#\n" +
	"\rServerCommand\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"Z\n" +
	"\x0eHydrateTrigger\x12!\n" +
	"\ftransfer_url\x18\x01 \x01(\tR\vtransferUrl\x12%\n" +
	"\x0etransfer_token\x18\x02 \x01(\tR\rtransferToken\"[\n" +
	"\x0fSnapshotTrigger\x12!\n" +
	"\ftransfer_url\x18\x01 \x01(\tR\vtransferUrl\x12%\n" +
	"\x0etransfer_token\x18\x02 \x01(\tR\rtransferToken\"\x1e\n" +
	"\bReadFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"8\n" +
	"\bEditFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x1f\n" +
	"\tListFiles\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"y\n" +
	"\n" +
	"TunnelDial\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1c\n" +
	"\n" +
	"tls_ca_pem\x18\x04 \x01(\tR\btlsCaPem\"\x83\x02\n" +
	"\rCommandResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x05error\x18\x02 \x01(\v2\".mcsd.controlplane.v1.CommandErrorR\x05error\x12'\n" +
	"\x0ecommand_output\x18\x03 \x01(\tH\x00R\rcommandOutput\x12#\n" +
	"\ffile_content\x18\x04 \x01(\fH\x00R\vfileContent\x12F\n" +
	"\ffile_listing\x18\x05 \x01(\v2!.mcsd.controlplane.v1.FileListingH\x00R\vfileListingB\b\n" +
	"\x06result\"f\n" +
	"\vFileListing\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.mcsd.controlplane.v1.FileEntryR\aentries\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"J\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\xba\x01\n" +
	"\fCommandError\x12:\n" +
	"\x04code\x18\x01 \x01(\x0e2&.mcsd.controlplane.v1.CommandErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12T\n" +
	"\x12file_access_reason\x18\x03 \x01(\x0e2&.mcsd.controlplane.v1.FileAccessReasonR\x10fileAccessReason\"\xb0\x02\n" +
	"\x05Event\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12I\n" +
	"\rstatus_change\x18\x02 \x01(\v2\".mcsd.controlplane.v1.StatusChangeH\x00R\fstatusChange\x12:\n" +
	"\blog_line\x18\x03 \x01(\v2\x1d.mcsd.controlplane.v1.LogLineH\x00R\alogLine\x129\n" +
	"\ametrics\x18\x04 \x01(\v2\x1d.mcsd.controlplane.v1.MetricsH\x00R\ametrics\x12?\n" +
	"\theartbeat\x18\x05 \x01(\v2\x1f.mcsd.controlplane.v1.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05event\"_\n" +
	"\fStatusChange\x127\n" +
	"\x05state\x18\x01 \x01(\x0e2!.mcsd.controlplane.v1.ServerStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"V\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x127\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x1f.mcsd.controlplane.v1.LogStreamR\x06stream\"n\n" +
	"\aMetrics\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\rR\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\rR\vplayerCount\"\v\n" +
	"\tHeartbeat*\x89\x01\n" +
	"\x13ExecutionDriverKind\x12%\n" +
	"!EXECUTION_DRIVER_KIND_UNSPECIFIED\x10\x00\x12&\n" +
	"\"EXECUTION_DRIVER_KIND_HOST_PROCESS\x10\x01\x12#\n" +
	"\x1fEXECUTION_DRIVER_KIND_CONTAINER\x10\x02*^\n" +
	"\n" +
	"LaunchMode\x12\x1b\n" +
	"\x17LAUNCH_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLAUNCH_MODE_JAR\x10\x01\x12\x1e\n" +
	"\x1aLAUNCH_MODE_FORGE_ARGSFILE\x10\x02*\xd7\x01\n" +
	"\x10FileAccessReason\x12\"\n" +
	"\x1eFILE_ACCESS_REASON_UNSPECIFIED\x10\x00\x12%\n" +
	"!FILE_ACCESS_REASON_IS_A_DIRECTORY\x10\x01\x12&\n" +
	"\"FILE_ACCESS_REASON_NOT_A_DIRECTORY\x10\x02\x12&\n" +
	"\"FILE_ACCESS_REASON_SYMLINK_REFUSED\x10\x03\x12(\n" +
	"$FILE_ACCESS_REASON_PAYLOAD_TOO_LARGE\x10\x04*\x8d\x03\n" +
	"\x10CommandErrorCode\x12\"\n" +
	"\x1eCOMMAND_ERROR_CODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#COMMAND_ERROR_CODE_SERVER_NOT_FOUND\x10\x01\x12$\n" +
	" COMMAND_ERROR_CODE_INVALID_STATE\x10\x02\x12)\n" +
	"%COMMAND_ERROR_CODE_DRIVER_UNAVAILABLE\x10\x03\x12)\n" +
	"%COMMAND_ERROR_CODE_FILE_ACCESS_DENIED\x10\x04\x12&\n" +
	"\"COMMAND_ERROR_CODE_TRANSFER_FAILED\x10\x05\x12\x1f\n" +
	"\x1bCOMMAND_ERROR_CODE_INTERNAL\x10\x06\x12$\n" +
	" COMMAND_ERROR_CODE_PORT_CONFLICT\x10\a\x12$\n" +
	" COMMAND_ERROR_CODE_IMAGE_MISSING\x10\b\x12\x1b\n" +
	"\x17COMMAND_ERROR_CODE_BUSY\x10\t*\xcc\x01\n" +
	"\vServerState\x12\x1c\n" +
	"\x18SERVER_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SERVER_STATE_STARTING\x10\x01\x12\x18\n" +
	"\x14SERVER_STATE_RUNNING\x10\x02\x12\x19\n" +
	"\x15SERVER_STATE_STOPPING\x10\x03\x12\x18\n" +
	"\x14SERVER_STATE_STOPPED\x10\x04\x12\x1b\n" +
	"\x17SERVER_STATE_RESTARTING\x10\x05\x12\x18\n" +
	"\x14SERVER_STATE_CRASHED\x10\x06*U\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x022e\n" +
	"\rWorkerService\x12T\n" +
	"\aSession\x12#.mcsd.controlplane.v1.WorkerMessage\x1a .mcsd.controlplane.v1.ApiMessage(\x010\x01B\x8f\x02\n" +
	"\x18com.mcsd.controlplane.v1B\x11ControlPlaneProtoP\x01Zngithub.com/mmiura-2351/mc-server-dashboard-v2/worker/internal/controlplane/mcsd/controlplane/v1;controlplanev1\xa2\x02\x03MCX\xaa\x02\x14Mcsd.Controlplane.V1\xca\x02\x14Mcsd\\Controlplane\\V1\xe2\x02 Mcsd\\Controlplane\\V1\\GPBMetadata\xea\x02\x16Mcsd::Controlplane::V1b\x06proto3"

var (
	file_mcsd_controlplane_v1_control_plane_proto_rawDescOnce sync.Once
	file_mcsd_controlplane_v1_control_plane_proto_rawDescData []byte
)

func file_mcsd_controlplane_v1_control_plane_proto_rawDescGZIP() []byte {
	file_mcsd_controlplane_v1_control_plane_proto_rawDescOnce.Do(func() {
		file_mcsd_controlplane_v1_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsd_controlplane_v1_control_plane_proto_rawDesc), len(file_mcsd_controlplane_v1_control_plane_proto_rawDesc)))
	})
	return file_mcsd_controlplane_v1_control_plane_proto_rawDescData
}

var file_mcsd_controlplane_v1_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_mcsd_controlplane_v1_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_mcsd_controlplane_v1_control_plane_proto_goTypes = []any{
	(ExecutionDriverKind)(0),      // 0: mcsd.controlplane.v1.ExecutionDriverKind
	(LaunchMode)(0),               // 1: mcsd.controlplane.v1.LaunchMode
	(FileAccessReason)(0),         // 2: mcsd.controlplane.v1.FileAccessReason
	(CommandErrorCode)(0),         // 3: mcsd.controlplane.v1.CommandErrorCode
	(ServerState)(0),              // 4: mcsd.controlplane.v1.ServerState
	(LogStream)(0),                // 5: mcsd.controlplane.v1.LogStream
	(*WorkerMessage)(nil),         // 6: mcsd.controlplane.v1.WorkerMessage
	(*ApiMessage)(nil),            // 7: mcsd.controlplane.v1.ApiMessage
	(*Register)(nil),              // 8: mcsd.controlplane.v1.Register
	(*HeldServer)(nil),            // 9: mcsd.controlplane.v1.HeldServer
	(*WorkerCapabilities)(nil),    // 10: mcsd.controlplane.v1.WorkerCapabilities
	(*HostResources)(nil),         // 11: mcsd.controlplane.v1.HostResources
	(*RegisterAck)(nil),           // 12: mcsd.controlplane.v1.RegisterAck
	(*ApiCommand)(nil),            // 13: mcsd.controlplane.v1.ApiCommand
	(*StartServer)(nil),           // 14: mcsd.controlplane.v1.StartServer
	(*StopServer)(nil),            // 15: mcsd.controlplane.v1.StopServer
	(*RestartServer)(nil),         // 16: mcsd.controlplane.v1.RestartServer
	(*ServerCommand)(nil),         // 17: mcsd.controlplane.v1.ServerCommand
	(*HydrateTrigger)(nil),        // 18: mcsd.controlplane.v1.HydrateTrigger
	(*SnapshotTrigger)(nil),       // 19: mcsd.controlplane.v1.SnapshotTrigger
	(*ReadFile)(nil),              // 20: mcsd.controlplane.v1.ReadFile
	(*EditFile)(nil),              // 21: mcsd.controlplane.v1.EditFile
	(*ListFiles)(nil),             // 22: mcsd.controlplane.v1.ListFiles
	(*TunnelDial)(nil),            // 23: mcsd.controlplane.v1.TunnelDial
	(*CommandResult)(nil),         // 24: mcsd.controlplane.v1.CommandResult
	(*FileListing)(nil),           // 25: mcsd.controlplane.v1.FileListing
	(*FileEntry)(nil),             // 26: mcsd.controlplane.v1.FileEntry
	(*CommandError)(nil),          // 27: mcsd.controlplane.v1.CommandError
	(*Event)(nil),                 // 28: mcsd.controlplane.v1.Event
	(*StatusChange)(nil),          // 29: mcsd.controlplane.v1.StatusChange
	(*LogLine)(nil),               // 30: mcsd.controlplane.v1.LogLine
	(*Metrics)(nil),               // 31: mcsd.controlplane.v1.Metrics
	(*Heartbeat)(nil),             // 32: mcsd.controlplane.v1.Heartbeat
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 34: google.protobuf.Duration
}
var file_mcsd_controlplane_v1_control_plane_proto_depIdxs = []int32{
	33, // 0: mcsd.controlplane.v1.WorkerMessage.emitted_at:type_name -> google.protobuf.Timestamp
	8,  // 1: mcsd.controlplane.v1.WorkerMessage.register:type_name -> mcsd.controlplane.v1.Register
	24, // 2: mcsd.controlplane.v1.WorkerMessage.command_result:type_name -> mcsd.controlplane.v1.CommandResult
	28, // 3: mcsd.controlplane.v1.WorkerMessage.event:type_name -> mcsd.controlplane.v1.Event
	33, // 4: mcsd.controlplane.v1.ApiMessage.sent_at:type_name -> google.protobuf.Timestamp
	12, // 5: mcsd.controlplane.v1.ApiMessage.register_ack:type_name -> mcsd.controlplane.v1.RegisterAck
	13, // 6: mcsd.controlplane.v1.ApiMessage.api_command:type_name -> mcsd.controlplane.v1.ApiCommand
	10, // 7: mcsd.controlplane.v1.Register.capabilities:type_name -> mcsd.controlplane.v1.WorkerCapabilities
	9,  // 8: mcsd.controlplane.v1.Register.held_servers:type_name -> mcsd.controlplane.v1.HeldServer
	0,  // 9: mcsd.controlplane.v1.WorkerCapabilities.drivers:type_name -> mcsd.controlplane.v1.ExecutionDriverKind
	11, // 10: mcsd.controlplane.v1.WorkerCapabilities.resources:type_name -> mcsd.controlplane.v1.HostResources
	34, // 11: mcsd.controlplane.v1.RegisterAck.heartbeat_interval:type_name -> google.protobuf.Duration
	34, // 12: mcsd.controlplane.v1.RegisterAck.transfer_deadline:type_name -> google.protobuf.Duration
	14, // 13: mcsd.controlplane.v1.ApiCommand.start:type_name -> mcsd.controlplane.v1.StartServer
	15, // 14: mcsd.controlplane.v1.ApiCommand.stop:type_name -> mcsd.controlplane.v1.StopServer
	16, // 15: mcsd.controlplane.v1.ApiCommand.restart:type_name -> mcsd.controlplane.v1.RestartServer
	17, // 16: mcsd.controlplane.v1.ApiCommand.server_command:type_name -> mcsd.controlplane.v1.ServerCommand
	18, // 17: mcsd.controlplane.v1.ApiCommand.hydrate:type_name -> mcsd.controlplane.v1.HydrateTrigger
	19, // 18: mcsd.controlplane.v1.ApiCommand.snapshot:type_name -> mcsd.controlplane.v1.SnapshotTrigger
	20, // 19: mcsd.controlplane.v1.ApiCommand.read_file:type_name -> mcsd.controlplane.v1.ReadFile
	21, // 20: mcsd.controlplane.v1.ApiCommand.edit_file:type_name -> mcsd.controlplane.v1.EditFile
	22, // 21: mcsd.controlplane.v1.ApiCommand.list_files:type_name -> mcsd.controlplane.v1.ListFiles
	23, // 22: mcsd.controlplane.v1.ApiCommand.tunnel_dial:type_name -> mcsd.controlplane.v1.TunnelDial
	0,  // 23: mcsd.controlplane.v1.StartServer.driver:type_name -> mcsd.controlplane.v1.ExecutionDriverKind
	1,  // 24: mcsd.controlplane.v1.StartServer.launch_mode:type_name -> mcsd.controlplane.v1.LaunchMode
	27, // 25: mcsd.controlplane.v1.CommandResult.error:type_name -> mcsd.controlplane.v1.CommandError
	25, // 26: mcsd.controlplane.v1.CommandResult.file_listing:type_name -> mcsd.controlplane.v1.FileListing
	26, // 27: mcsd.controlplane.v1.FileListing.entries:type_name -> mcsd.controlplane.v1.FileEntry
	3,  // 28: mcsd.controlplane.v1.CommandError.code:type_name -> mcsd.controlplane.v1.CommandErrorCode
	2,  // 29: mcsd.controlplane.v1.CommandError.file_access_reason:type_name -> mcsd.controlplane.v1.FileAccessReason
	29, // 30: mcsd.controlplane.v1.Event.status_change:type_name -> mcsd.controlplane.v1.StatusChange
	30, // 31: mcsd.controlplane.v1.Event.log_line:type_name -> mcsd.controlplane.v1.LogLine
	31, // 32: mcsd.controlplane.v1.Event.metrics:type_name -> mcsd.controlplane.v1.Metrics
	32, // 33: mcsd.controlplane.v1.Event.heartbeat:type_name -> mcsd.controlplane.v1.Heartbeat
	4,  // 34: mcsd.controlplane.v1.StatusChange.state:type_name -> mcsd.controlplane.v1.ServerState
	5,  // 35: mcsd.controlplane.v1.LogLine.stream:type_name -> mcsd.controlplane.v1.LogStream
	6,  // 36: mcsd.controlplane.v1.WorkerService.Session:input_type -> mcsd.controlplane.v1.WorkerMessage
	7,  // 37: mcsd.controlplane.v1.WorkerService.Session:output_type -> mcsd.controlplane.v1.ApiMessage
	37, // [37:38] is the sub-list for method output_type
	36, // [36:37] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_mcsd_controlplane_v1_control_plane_proto_init() }
func file_mcsd_controlplane_v1_control_plane_proto_init() {
	if File_mcsd_controlplane_v1_control_plane_proto != nil {
		return
	}
	file_mcsd_controlplane_v1_control_plane_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_CommandResult)(nil),
		(*WorkerMessage_Event)(nil),
	}
	file_mcsd_controlplane_v1_control_plane_proto_msgTypes[1].OneofWrappers = []any{
		(*ApiMessage_RegisterAck)(nil),
		(*ApiMessage_ApiCommand)(nil),
	}
	file_mcsd_controlplane_v1_control_plane_proto_msgTypes[7].OneofWrappers = []any{
		(*ApiCommand_Start)(nil),
		(*ApiCommand_Stop)(nil),
		(*ApiCommand_Restart)(nil),
		(*ApiCommand_ServerCommand)(nil),
		(*ApiCommand_Hydrate)(nil),
		(*ApiCommand_Snapshot)(nil),
		(*ApiCommand_ReadFile)(nil),
		(*ApiCommand_EditFile)(nil),
		(*ApiCommand_ListFiles)(nil),
		(*ApiCommand_TunnelDial)(nil),
	}
	file_mcsd_controlplane_v1_control_plane_proto_msgTypes[18].OneofWrappers = []any{
		(*CommandResult_CommandOutput)(nil),
		(*CommandResult_FileContent)(nil),
		(*CommandResult_FileListing)(nil),
	}
	file_mcsd_controlplane_v1_control_plane_proto_msgTypes[22].OneofWrappers = []any{
		(*Event_StatusChange)(nil),
		(*Event_LogLine)(nil),
		(*Event_Metrics)(nil),
		(*Event_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsd_controlplane_v1_control_plane_proto_rawDesc), len(file_mcsd_controlplane_v1_control_plane_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsd_controlplane_v1_control_plane_proto_goTypes,
		DependencyIndexes: file_mcsd_controlplane_v1_control_plane_proto_depIdxs,
		EnumInfos:         file_mcsd_controlplane_v1_control_plane_proto_enumTypes,
		MessageInfos:      file_mcsd_controlplane_v1_control_plane_proto_msgTypes,
	}.Build()
	File_mcsd_controlplane_v1_control_plane_proto = out.File
	file_mcsd_controlplane_v1_control_plane_proto_goTypes = nil
	file_mcsd_controlplane_v1_control_plane_proto_depIdxs = nil
}
