"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The Minecraft Server Dashboard v2 relay-to-API contract.

RelayService is served on the API's existing gRPC listener alongside
WorkerService. All RPCs are relay-initiated (unary); the relay has no
command inbox. Transport posture matches the Worker: server-side TLS plus a
shared-secret credential in call metadata, but a separate credential
(relay.credential) so relay and Worker credentials rotate independently.

See docs/app/RELAY.md Section 6 for the full relay-to-API contract and
Section 5 for the tunnel contract (TunnelDial lives in the controlplane
package — RELAY.md Section 5 — because it rides the existing Worker stream).
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _JoinIntent:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JoinIntentEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JoinIntent.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JOIN_INTENT_UNSPECIFIED: _JoinIntent.ValueType  # 0
    JOIN_INTENT_STATUS: _JoinIntent.ValueType  # 1
    """STATUS is a server-list status ping (next_state = 1 in the Minecraft
    handshake). RELAY.md Section 7.
    """
    JOIN_INTENT_LOGIN: _JoinIntent.ValueType  # 2
    """LOGIN is a full login attempt (next_state = 2 in the Minecraft
    handshake). RELAY.md Section 4.
    """

class JoinIntent(_JoinIntent, metaclass=_JoinIntentEnumTypeWrapper):
    """---------------------------------------------------------------------------
    ResolveJoin (RELAY.md Sections 4 and 6)
    ---------------------------------------------------------------------------

    JoinIntent distinguishes a status ping from a login attempt. Both intents
    dispatch a TunnelDial for running servers — the relay needs the tunnel even
    for STATUS pings (cache miss) to fetch the real Minecraft status data
    (RELAY.md Section 7). The relay uses the intent on its side to decide how
    to handle the tunneled connection (one-shot status exchange vs full login
    splice) and the stopped-server in-protocol response.
    """

JOIN_INTENT_UNSPECIFIED: JoinIntent.ValueType  # 0
JOIN_INTENT_STATUS: JoinIntent.ValueType  # 1
"""STATUS is a server-list status ping (next_state = 1 in the Minecraft
handshake). RELAY.md Section 7.
"""
JOIN_INTENT_LOGIN: JoinIntent.ValueType  # 2
"""LOGIN is a full login attempt (next_state = 2 in the Minecraft
handshake). RELAY.md Section 4.
"""
Global___JoinIntent: _TypeAlias = JoinIntent  # noqa: Y015

class _JoinDecision:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JoinDecisionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JoinDecision.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JOIN_DECISION_UNSPECIFIED: _JoinDecision.ValueType  # 0
    JOIN_DECISION_TUNNEL: _JoinDecision.ValueType  # 1
    """TUNNEL means the server is running and the Worker has been given a
    TunnelDial command. The relay waits for the Worker's dial-back and then
    splices. RELAY.md Section 4.
    """
    JOIN_DECISION_STOPPED: _JoinDecision.ValueType  # 2
    """STOPPED means the slug resolves to a known server that is not currently
    running. The relay responds in-protocol (disconnect reason / status MOTD).
    RELAY.md Section 7.
    """
    JOIN_DECISION_NOT_FOUND: _JoinDecision.ValueType  # 3
    """NOT_FOUND means the slug does not resolve to any known server. The relay
    drops the connection silently. RELAY.md Section 7.
    """

class JoinDecision(_JoinDecision, metaclass=_JoinDecisionEnumTypeWrapper):
    """JoinDecision is the routing outcome the API returns to the relay."""

JOIN_DECISION_UNSPECIFIED: JoinDecision.ValueType  # 0
JOIN_DECISION_TUNNEL: JoinDecision.ValueType  # 1
"""TUNNEL means the server is running and the Worker has been given a
TunnelDial command. The relay waits for the Worker's dial-back and then
splices. RELAY.md Section 4.
"""
JOIN_DECISION_STOPPED: JoinDecision.ValueType  # 2
"""STOPPED means the slug resolves to a known server that is not currently
running. The relay responds in-protocol (disconnect reason / status MOTD).
RELAY.md Section 7.
"""
JOIN_DECISION_NOT_FOUND: JoinDecision.ValueType  # 3
"""NOT_FOUND means the slug does not resolve to any known server. The relay
drops the connection silently. RELAY.md Section 7.
"""
Global___JoinDecision: _TypeAlias = JoinDecision  # noqa: Y015

class _SessionSource:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SessionSourceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SessionSource.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SESSION_SOURCE_UNSPECIFIED: _SessionSource.ValueType  # 0
    SESSION_SOURCE_JAVA: _SessionSource.ValueType  # 1
    """JAVA is a Minecraft Java Edition login-session from the game listener
    (RELAY.md Section 8).
    """
    SESSION_SOURCE_BEDROCK: _SessionSource.ValueType  # 2
    """BEDROCK is a Bedrock (Geyser) flow-session from the Bedrock tunnel path
    (epic #1540, issue #1904).
    """

class SessionSource(_SessionSource, metaclass=_SessionSourceEnumTypeWrapper):
    """SessionSource is the relay ingress path a session was accepted on, so the
    session history can label Java and Bedrock rows honestly (issue #1912). A
    Bedrock flow-session carries no claimed identity (the relay never sees
    Floodgate username/UUID), which without this discriminator is
    indistinguishable from a Java login-session whose identity was unparseable.
    """

SESSION_SOURCE_UNSPECIFIED: SessionSource.ValueType  # 0
SESSION_SOURCE_JAVA: SessionSource.ValueType  # 1
"""JAVA is a Minecraft Java Edition login-session from the game listener
(RELAY.md Section 8).
"""
SESSION_SOURCE_BEDROCK: SessionSource.ValueType  # 2
"""BEDROCK is a Bedrock (Geyser) flow-session from the Bedrock tunnel path
(epic #1540, issue #1904).
"""
Global___SessionSource: _TypeAlias = SessionSource  # noqa: Y015

@_typing.final
class RegisterRequest(_message.Message):
    """---------------------------------------------------------------------------
    Register (RELAY.md Section 6)
    ---------------------------------------------------------------------------

    RegisterRequest carries the relay's tunnel endpoint and active session set
    to the API on startup or reconnect.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TUNNEL_ENDPOINT_FIELD_NUMBER: _builtins.int
    TUNNEL_CA_PEM_FIELD_NUMBER: _builtins.int
    ACTIVE_SESSION_IDS_FIELD_NUMBER: _builtins.int
    tunnel_endpoint: _builtins.str
    """tunnel_endpoint is the host:port the API delivers to Workers in TunnelDial
    commands so they know where to dial back. Required. RELAY.md Section 5.
    """
    tunnel_ca_pem: _builtins.str
    """tunnel_ca_pem is the PEM-encoded CA bundle the API includes in TunnelDial
    commands so Workers can verify the relay's tunnel certificate. Empty means
    system roots (public CA). RELAY.md Section 5.
    """
    @_builtins.property
    def active_session_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """active_session_ids is the set of session UUIDs currently live on the
        relay. The API closes game_session rows that are open but absent from this
        set — orphan healing after a relay crash. RELAY.md Section 6.
        """

    def __init__(
        self,
        *,
        tunnel_endpoint: _builtins.str = ...,
        tunnel_ca_pem: _builtins.str = ...,
        active_session_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_session_ids", b"active_session_ids", "tunnel_ca_pem", b"tunnel_ca_pem", "tunnel_endpoint", b"tunnel_endpoint"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterRequest: _TypeAlias = RegisterRequest  # noqa: Y015

@_typing.final
class RegisterResponse(_message.Message):
    """RegisterResponse carries the deployment-level base domain back to the relay
    so it has a single config source for hostname routing. RELAY.md Section 6.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BASE_DOMAIN_FIELD_NUMBER: _builtins.int
    base_domain: _builtins.str
    """base_domain is the relay's routing domain (e.g. "mc.example.com").
    Slugs are resolved relative to this; a handshake address that does not
    end with ".<base_domain>" is treated as unknown. RELAY.md Section 3.
    """
    def __init__(
        self,
        *,
        base_domain: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base_domain", b"base_domain"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterResponse: _TypeAlias = RegisterResponse  # noqa: Y015

@_typing.final
class ResolveJoinRequest(_message.Message):
    """ResolveJoinRequest asks the API for a routing decision for one incoming
    player connection.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SLUG_FIELD_NUMBER: _builtins.int
    PLAYER_IP_FIELD_NUMBER: _builtins.int
    INTENT_FIELD_NUMBER: _builtins.int
    slug: _builtins.str
    """slug is the server identifier extracted from the handshake address by
    stripping the base_domain suffix. RELAY.md Section 3.
    """
    player_ip: _builtins.str
    """player_ip is the player's source address as seen by the relay (PII;
    recorded in game_session). RELAY.md Section 8.
    """
    intent: Global___JoinIntent.ValueType
    """intent distinguishes a status ping from a login attempt. RELAY.md
    Sections 6 and 7.
    """
    def __init__(
        self,
        *,
        slug: _builtins.str = ...,
        player_ip: _builtins.str = ...,
        intent: Global___JoinIntent.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["intent", b"intent", "player_ip", b"player_ip", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolveJoinRequest: _TypeAlias = ResolveJoinRequest  # noqa: Y015

@_typing.final
class ResolveJoinResponse(_message.Message):
    """ResolveJoinResponse carries the routing decision and, for TUNNEL decisions,
    the single-use token the Worker must present. RELAY.md Section 6.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DECISION_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    SERVER_ID_FIELD_NUMBER: _builtins.int
    decision: Global___JoinDecision.ValueType
    """decision is the routing outcome. RELAY.md Section 6."""
    token: _builtins.str
    """token is the single-use 128-bit session token the Worker presents on the
    tunnel dial-back to identify its connection. Set only when decision is
    TUNNEL. The token expires in 10 s (RELAY.md Section 4).
    """
    display_name: _builtins.str
    """display_name is the server's human-readable name, used by the relay to
    synthesize the stopped-server in-protocol response. Set only when
    decision is STOPPED. RELAY.md Section 7.
    """
    server_id: _builtins.str
    """server_id is the API's identifier for the server the player joined, which
    the relay carries into SessionStart.server_id (the relay cannot resolve
    slug→server itself). Set only when decision is TUNNEL. RELAY.md Section 8.
    """
    def __init__(
        self,
        *,
        decision: Global___JoinDecision.ValueType = ...,
        token: _builtins.str = ...,
        display_name: _builtins.str = ...,
        server_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["decision", b"decision", "display_name", b"display_name", "server_id", b"server_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolveJoinResponse: _TypeAlias = ResolveJoinResponse  # noqa: Y015

@_typing.final
class ReportSessionsRequest(_message.Message):
    """---------------------------------------------------------------------------
    ReportSessions (RELAY.md Sections 6 and 8)
    ---------------------------------------------------------------------------

    ReportSessionsRequest delivers a batch of session lifecycle events to the
    API. Batches are flushed every ~5 s or 100 events. RELAY.md Section 6.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EVENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___SessionEvent]:
        """events is the batch of session lifecycle events. RELAY.md Section 6."""

    def __init__(
        self,
        *,
        events: _abc.Iterable[Global___SessionEvent] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events", b"events"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReportSessionsRequest: _TypeAlias = ReportSessionsRequest  # noqa: Y015

@_typing.final
class ReportSessionsResponse(_message.Message):
    """ReportSessionsResponse acknowledges a batch. Empty: the relay does not need
    per-event acks, only an error on transient failure to trigger a retry.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReportSessionsResponse: _TypeAlias = ReportSessionsResponse  # noqa: Y015

@_typing.final
class SessionEvent(_message.Message):
    """SessionEvent is one lifecycle event in a ReportSessions batch.
    Exactly one of start or end is set. RELAY.md Section 6.
    """

    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    END_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def start(self) -> Global___SessionStart:
        """start records a new accepted player session. RELAY.md Section 8."""

    @_builtins.property
    def end(self) -> Global___SessionEnd:
        """end records the closing of a session. RELAY.md Section 8."""

    def __init__(
        self,
        *,
        start: Global___SessionStart | None = ...,
        end: Global___SessionEnd | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "event", b"event", "start", b"start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "event", b"event", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["start", "end"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___SessionEvent: _TypeAlias = SessionEvent  # noqa: Y015

@_typing.final
class SessionStart(_message.Message):
    """SessionStart records the opening of a player session. Fields mirror the
    game_session table columns (RELAY.md Section 14).
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    SERVER_ID_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    PLAYER_IP_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    PLAYER_UUID_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    """session_id is the relay-minted UUID, the idempotency key for upserts."""
    server_id: _builtins.str
    """server_id is the API's identifier for the server the player joined."""
    slug: _builtins.str
    """slug is the hostname label used at join time (historical value; slugs are
    renameable so this captures what the player typed). RELAY.md Section 14.
    """
    player_ip: _builtins.str
    """player_ip is the player's source address as seen by the relay (PII).
    RELAY.md Section 8.
    """
    username: _builtins.str
    """username is the name claimed in the Minecraft Login Start packet.
    Pre-authentication; with online-mode on, a meaningful-duration session
    implies a verified identity. Empty string means absent or unparseable
    (maps to NULL in the game_session table — RELAY.md Sections 7 and 14).
    RELAY.md Section 8.
    """
    player_uuid: _builtins.str
    """player_uuid is the UUID claimed in the Login Start packet (present on
    protocols that send it; absent on older protocol versions). Empty string
    means absent or unparseable (maps to NULL in the game_session table —
    RELAY.md Sections 7 and 14).
    """
    source: Global___SessionSource.ValueType
    """source is the relay ingress path (Java game listener vs Bedrock tunnel) the
    session was accepted on, so the history can label the row honestly
    (issue #1912). Unset means an older relay that predates the field; the API
    stores it as the legacy/unspecified source.
    """
    @_builtins.property
    def started_at(self) -> _timestamp_pb2.Timestamp:
        """started_at is when the relay accepted the session (relay clock)."""

    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        server_id: _builtins.str = ...,
        slug: _builtins.str = ...,
        player_ip: _builtins.str = ...,
        username: _builtins.str = ...,
        player_uuid: _builtins.str = ...,
        started_at: _timestamp_pb2.Timestamp | None = ...,
        source: Global___SessionSource.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["started_at", b"started_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["player_ip", b"player_ip", "player_uuid", b"player_uuid", "server_id", b"server_id", "session_id", b"session_id", "slug", b"slug", "source", b"source", "started_at", b"started_at", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionStart: _TypeAlias = SessionStart  # noqa: Y015

@_typing.final
class SessionEnd(_message.Message):
    """SessionEnd records the closing of a player session."""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    ENDED_AT_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    """session_id identifies the session being closed (matches a prior
    SessionStart.session_id).
    """
    @_builtins.property
    def ended_at(self) -> _timestamp_pb2.Timestamp:
        """ended_at is when the relay observed the session close (relay clock)."""

    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        ended_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ended_at", b"ended_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ended_at", b"ended_at", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionEnd: _TypeAlias = SessionEnd  # noqa: Y015

@_typing.final
class ValidateBedrockTunnelRequest(_message.Message):
    """---------------------------------------------------------------------------
    ValidateBedrockTunnel (epic #1540, issue #1544)
    ---------------------------------------------------------------------------

    ValidateBedrockTunnelRequest carries the credential a Worker presented on
    its Bedrock QUIC dial-out, for the relay to confirm against the API
    (mcsd.controlplane.v1.OpenBedrockTunnel carries the same three values to
    the Worker).
    """

    DESCRIPTOR: _descriptor.Descriptor

    SERVER_ID_FIELD_NUMBER: _builtins.int
    BEDROCK_PORT_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    server_id: _builtins.str
    """server_id identifies the local server the dial claims to be for."""
    bedrock_port: _builtins.int
    """bedrock_port is the public UDP port the dial claims to serve."""
    token: _builtins.str
    """token is the credential the Worker presented on the QUIC dial-out."""
    def __init__(
        self,
        *,
        server_id: _builtins.str = ...,
        bedrock_port: _builtins.int = ...,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bedrock_port", b"bedrock_port", "server_id", b"server_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateBedrockTunnelRequest: _TypeAlias = ValidateBedrockTunnelRequest  # noqa: Y015

@_typing.final
class ValidateBedrockTunnelResponse(_message.Message):
    """ValidateBedrockTunnelResponse reports whether the presented credential
    matches the tunnel the API currently has open for that server.
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALID_FIELD_NUMBER: _builtins.int
    valid: _builtins.bool
    """valid is true when (server_id, bedrock_port, token) matches the API's
    current record for an open Bedrock tunnel on that server.
    """
    def __init__(
        self,
        *,
        valid: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["valid", b"valid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateBedrockTunnelResponse: _TypeAlias = ValidateBedrockTunnelResponse  # noqa: Y015
