# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcsd.relay.v1 import relay_pb2 as mcsd_dot_relay_dot_v1_dot_relay__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcsd/relay/v1/relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelayServiceStub(object):
    """RelayService is the gRPC service the relay calls on the API. All three RPCs
    are unary (RELAY.md Section 6): the relay has no persistent stream and no
    command inbox; every call is relay-initiated.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/mcsd.relay.v1.RelayService/Register',
                request_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.RegisterRequest.SerializeToString,
                response_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.ResolveJoin = channel.unary_unary(
                '/mcsd.relay.v1.RelayService/ResolveJoin',
                request_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ResolveJoinRequest.SerializeToString,
                response_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ResolveJoinResponse.FromString,
                _registered_method=True)
        self.ReportSessions = channel.unary_unary(
                '/mcsd.relay.v1.RelayService/ReportSessions',
                request_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ReportSessionsRequest.SerializeToString,
                response_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ReportSessionsResponse.FromString,
                _registered_method=True)
        self.ValidateBedrockTunnel = channel.unary_unary(
                '/mcsd.relay.v1.RelayService/ValidateBedrockTunnel',
                request_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ValidateBedrockTunnelRequest.SerializeToString,
                response_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ValidateBedrockTunnelResponse.FromString,
                _registered_method=True)


class RelayServiceServicer(object):
    """RelayService is the gRPC service the relay calls on the API. All three RPCs
    are unary (RELAY.md Section 6): the relay has no persistent stream and no
    command inbox; every call is relay-initiated.
    """

    def Register(self, request, context):
        """Register is called at relay startup and on reconnect. The API stores the
        relay's tunnel endpoint and CA for use in TunnelDial commands, and closes
        any game_session rows open but absent from the relay's active set
        (orphan healing after a relay crash). RELAY.md Section 6.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveJoin(self, request, context):
        """ResolveJoin is the per-connection routing decision. The relay calls it
        once per incoming player connection after parsing the Minecraft handshake.
        The API returns a routing decision and, on a TUNNEL decision, dispatches
        a TunnelDial command to the assigned Worker as a side effect (Section 4).
        RELAY.md Sections 4 and 6.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSessions(self, request, context):
        """ReportSessions delivers batched session lifecycle events (SessionStart and
        SessionEnd). The API persists them as game_session rows; upsert-on-id
        makes retries after transient errors safe. RELAY.md Sections 6 and 8.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateBedrockTunnel(self, request, context):
        """ValidateBedrockTunnel is called by the relay when it accepts a Worker's
        QUIC dial-out for a Bedrock tunnel (epic #1540, issue #1544). Unlike the
        per-player join token -- which the relay matches locally because it
        minted the waiter itself via its own ResolveJoin call -- the Bedrock
        tunnel is opened API-initiated at server-running time, so the relay has
        no prior waiter to match against and asks the API to confirm the token
        instead. This keeps the relay itself free of a persistent server list;
        its own state stays limited to in-flight tunnel connections.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.RegisterRequest.FromString,
                    response_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.RegisterResponse.SerializeToString,
            ),
            'ResolveJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveJoin,
                    request_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ResolveJoinRequest.FromString,
                    response_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ResolveJoinResponse.SerializeToString,
            ),
            'ReportSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSessions,
                    request_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ReportSessionsRequest.FromString,
                    response_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ReportSessionsResponse.SerializeToString,
            ),
            'ValidateBedrockTunnel': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateBedrockTunnel,
                    request_deserializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ValidateBedrockTunnelRequest.FromString,
                    response_serializer=mcsd_dot_relay_dot_v1_dot_relay__pb2.ValidateBedrockTunnelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcsd.relay.v1.RelayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcsd.relay.v1.RelayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelayService(object):
    """RelayService is the gRPC service the relay calls on the API. All three RPCs
    are unary (RELAY.md Section 6): the relay has no persistent stream and no
    command inbox; every call is relay-initiated.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcsd.relay.v1.RelayService/Register',
            mcsd_dot_relay_dot_v1_dot_relay__pb2.RegisterRequest.SerializeToString,
            mcsd_dot_relay_dot_v1_dot_relay__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcsd.relay.v1.RelayService/ResolveJoin',
            mcsd_dot_relay_dot_v1_dot_relay__pb2.ResolveJoinRequest.SerializeToString,
            mcsd_dot_relay_dot_v1_dot_relay__pb2.ResolveJoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcsd.relay.v1.RelayService/ReportSessions',
            mcsd_dot_relay_dot_v1_dot_relay__pb2.ReportSessionsRequest.SerializeToString,
            mcsd_dot_relay_dot_v1_dot_relay__pb2.ReportSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateBedrockTunnel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcsd.relay.v1.RelayService/ValidateBedrockTunnel',
            mcsd_dot_relay_dot_v1_dot_relay__pb2.ValidateBedrockTunnelRequest.SerializeToString,
            mcsd_dot_relay_dot_v1_dot_relay__pb2.ValidateBedrockTunnelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
