"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The Minecraft Server Dashboard v2 relay-to-API contract.

RelayService is served on the API's existing gRPC listener alongside
WorkerService. All RPCs are relay-initiated (unary); the relay has no
command inbox. Transport posture matches the Worker: server-side TLS plus a
shared-secret credential in call metadata, but a separate credential
(relay.credential) so relay and Worker credentials rotate independently.

See docs/app/RELAY.md Section 6 for the full relay-to-API contract and
Section 5 for the tunnel contract (TunnelDial lives in the controlplane
package — RELAY.md Section 5 — because it rides the existing Worker stream).
"""

from collections import abc as _abc
from grpc import aio as _aio
from mcsd.relay.v1 import relay_pb2 as _relay_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RelayServiceStub:
    """RelayService is the gRPC service the relay calls on the API. All three RPCs
    are unary (RELAY.md Section 6): the relay has no persistent stream and no
    command inbox; every call is relay-initiated.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RelayServiceAsyncStub: ...
    Register: _grpc.UnaryUnaryMultiCallable[_relay_pb2.RegisterRequest, _relay_pb2.RegisterResponse]
    """Register is called at relay startup and on reconnect. The API stores the
    relay's tunnel endpoint and CA for use in TunnelDial commands, and closes
    any game_session rows open but absent from the relay's active set
    (orphan healing after a relay crash). RELAY.md Section 6.
    """
    ResolveJoin: _grpc.UnaryUnaryMultiCallable[_relay_pb2.ResolveJoinRequest, _relay_pb2.ResolveJoinResponse]
    """ResolveJoin is the per-connection routing decision. The relay calls it
    once per incoming player connection after parsing the Minecraft handshake.
    The API returns a routing decision and, on a TUNNEL decision, dispatches
    a TunnelDial command to the assigned Worker as a side effect (Section 4).
    RELAY.md Sections 4 and 6.
    """
    ReportSessions: _grpc.UnaryUnaryMultiCallable[_relay_pb2.ReportSessionsRequest, _relay_pb2.ReportSessionsResponse]
    """ReportSessions delivers batched session lifecycle events (SessionStart and
    SessionEnd). The API persists them as game_session rows; upsert-on-id
    makes retries after transient errors safe. RELAY.md Sections 6 and 8.
    """

@_typing.type_check_only
class RelayServiceAsyncStub(RelayServiceStub):
    """RelayService is the gRPC service the relay calls on the API. All three RPCs
    are unary (RELAY.md Section 6): the relay has no persistent stream and no
    command inbox; every call is relay-initiated.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Register: _aio.UnaryUnaryMultiCallable[_relay_pb2.RegisterRequest, _relay_pb2.RegisterResponse]  # type: ignore[assignment]
    """Register is called at relay startup and on reconnect. The API stores the
    relay's tunnel endpoint and CA for use in TunnelDial commands, and closes
    any game_session rows open but absent from the relay's active set
    (orphan healing after a relay crash). RELAY.md Section 6.
    """
    ResolveJoin: _aio.UnaryUnaryMultiCallable[_relay_pb2.ResolveJoinRequest, _relay_pb2.ResolveJoinResponse]  # type: ignore[assignment]
    """ResolveJoin is the per-connection routing decision. The relay calls it
    once per incoming player connection after parsing the Minecraft handshake.
    The API returns a routing decision and, on a TUNNEL decision, dispatches
    a TunnelDial command to the assigned Worker as a side effect (Section 4).
    RELAY.md Sections 4 and 6.
    """
    ReportSessions: _aio.UnaryUnaryMultiCallable[_relay_pb2.ReportSessionsRequest, _relay_pb2.ReportSessionsResponse]  # type: ignore[assignment]
    """ReportSessions delivers batched session lifecycle events (SessionStart and
    SessionEnd). The API persists them as game_session rows; upsert-on-id
    makes retries after transient errors safe. RELAY.md Sections 6 and 8.
    """

class RelayServiceServicer(metaclass=_abc_1.ABCMeta):
    """RelayService is the gRPC service the relay calls on the API. All three RPCs
    are unary (RELAY.md Section 6): the relay has no persistent stream and no
    command inbox; every call is relay-initiated.
    """

    @_abc_1.abstractmethod
    def Register(
        self,
        request: _relay_pb2.RegisterRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_relay_pb2.RegisterResponse, _abc.Awaitable[_relay_pb2.RegisterResponse]]:
        """Register is called at relay startup and on reconnect. The API stores the
        relay's tunnel endpoint and CA for use in TunnelDial commands, and closes
        any game_session rows open but absent from the relay's active set
        (orphan healing after a relay crash). RELAY.md Section 6.
        """

    @_abc_1.abstractmethod
    def ResolveJoin(
        self,
        request: _relay_pb2.ResolveJoinRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_relay_pb2.ResolveJoinResponse, _abc.Awaitable[_relay_pb2.ResolveJoinResponse]]:
        """ResolveJoin is the per-connection routing decision. The relay calls it
        once per incoming player connection after parsing the Minecraft handshake.
        The API returns a routing decision and, on a TUNNEL decision, dispatches
        a TunnelDial command to the assigned Worker as a side effect (Section 4).
        RELAY.md Sections 4 and 6.
        """

    @_abc_1.abstractmethod
    def ReportSessions(
        self,
        request: _relay_pb2.ReportSessionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_relay_pb2.ReportSessionsResponse, _abc.Awaitable[_relay_pb2.ReportSessionsResponse]]:
        """ReportSessions delivers batched session lifecycle events (SessionStart and
        SessionEnd). The API persists them as game_session rows; upsert-on-id
        makes retries after transient errors safe. RELAY.md Sections 6 and 8.
        """

def add_RelayServiceServicer_to_server(servicer: RelayServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
