// The Minecraft Server Dashboard v2 relay-to-API contract.
//
// RelayService is served on the API's existing gRPC listener alongside
// WorkerService. All RPCs are relay-initiated (unary); the relay has no
// command inbox. Transport posture matches the Worker: server-side TLS plus a
// shared-secret credential in call metadata, but a separate credential
// (relay.credential) so relay and Worker credentials rotate independently.
//
// See docs/app/RELAY.md Section 6 for the full relay-to-API contract and
// Section 5 for the tunnel contract (TunnelDial lives in the controlplane
// package — RELAY.md Section 5 — because it rides the existing Worker stream).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcsd/relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinIntent distinguishes a status ping from a login attempt. Both intents
// dispatch a TunnelDial for running servers — the relay needs the tunnel even
// for STATUS pings (cache miss) to fetch the real Minecraft status data
// (RELAY.md Section 7). The relay uses the intent on its side to decide how
// to handle the tunneled connection (one-shot status exchange vs full login
// splice) and the stopped-server in-protocol response.
type JoinIntent int32

const (
	JoinIntent_JOIN_INTENT_UNSPECIFIED JoinIntent = 0
	// STATUS is a server-list status ping (next_state = 1 in the Minecraft
	// handshake). RELAY.md Section 7.
	JoinIntent_JOIN_INTENT_STATUS JoinIntent = 1
	// LOGIN is a full login attempt (next_state = 2 in the Minecraft
	// handshake). RELAY.md Section 4.
	JoinIntent_JOIN_INTENT_LOGIN JoinIntent = 2
)

// Enum value maps for JoinIntent.
var (
	JoinIntent_name = map[int32]string{
		0: "JOIN_INTENT_UNSPECIFIED",
		1: "JOIN_INTENT_STATUS",
		2: "JOIN_INTENT_LOGIN",
	}
	JoinIntent_value = map[string]int32{
		"JOIN_INTENT_UNSPECIFIED": 0,
		"JOIN_INTENT_STATUS":      1,
		"JOIN_INTENT_LOGIN":       2,
	}
)

func (x JoinIntent) Enum() *JoinIntent {
	p := new(JoinIntent)
	*p = x
	return p
}

func (x JoinIntent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinIntent) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (JoinIntent) Type() protoreflect.EnumType {
	return &file_mcsd_relay_v1_relay_proto_enumTypes[0]
}

func (x JoinIntent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinIntent.Descriptor instead.
func (JoinIntent) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

// JoinDecision is the routing outcome the API returns to the relay.
type JoinDecision int32

const (
	JoinDecision_JOIN_DECISION_UNSPECIFIED JoinDecision = 0
	// TUNNEL means the server is running and the Worker has been given a
	// TunnelDial command. The relay waits for the Worker's dial-back and then
	// splices. RELAY.md Section 4.
	JoinDecision_JOIN_DECISION_TUNNEL JoinDecision = 1
	// STOPPED means the slug resolves to a known server that is not currently
	// running. The relay responds in-protocol (disconnect reason / status MOTD).
	// RELAY.md Section 7.
	JoinDecision_JOIN_DECISION_STOPPED JoinDecision = 2
	// NOT_FOUND means the slug does not resolve to any known server. The relay
	// drops the connection silently. RELAY.md Section 7.
	JoinDecision_JOIN_DECISION_NOT_FOUND JoinDecision = 3
)

// Enum value maps for JoinDecision.
var (
	JoinDecision_name = map[int32]string{
		0: "JOIN_DECISION_UNSPECIFIED",
		1: "JOIN_DECISION_TUNNEL",
		2: "JOIN_DECISION_STOPPED",
		3: "JOIN_DECISION_NOT_FOUND",
	}
	JoinDecision_value = map[string]int32{
		"JOIN_DECISION_UNSPECIFIED": 0,
		"JOIN_DECISION_TUNNEL":      1,
		"JOIN_DECISION_STOPPED":     2,
		"JOIN_DECISION_NOT_FOUND":   3,
	}
)

func (x JoinDecision) Enum() *JoinDecision {
	p := new(JoinDecision)
	*p = x
	return p
}

func (x JoinDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_relay_v1_relay_proto_enumTypes[1].Descriptor()
}

func (JoinDecision) Type() protoreflect.EnumType {
	return &file_mcsd_relay_v1_relay_proto_enumTypes[1]
}

func (x JoinDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinDecision.Descriptor instead.
func (JoinDecision) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

// SessionSource is the relay ingress path a session was accepted on, so the
// session history can label Java and Bedrock rows honestly (issue #1912). A
// Bedrock flow-session carries no claimed identity (the relay never sees
// Floodgate username/UUID), which without this discriminator is
// indistinguishable from a Java login-session whose identity was unparseable.
type SessionSource int32

const (
	SessionSource_SESSION_SOURCE_UNSPECIFIED SessionSource = 0
	// JAVA is a Minecraft Java Edition login-session from the game listener
	// (RELAY.md Section 8).
	SessionSource_SESSION_SOURCE_JAVA SessionSource = 1
	// BEDROCK is a Bedrock (Geyser) flow-session from the Bedrock tunnel path
	// (epic #1540, issue #1904).
	SessionSource_SESSION_SOURCE_BEDROCK SessionSource = 2
)

// Enum value maps for SessionSource.
var (
	SessionSource_name = map[int32]string{
		0: "SESSION_SOURCE_UNSPECIFIED",
		1: "SESSION_SOURCE_JAVA",
		2: "SESSION_SOURCE_BEDROCK",
	}
	SessionSource_value = map[string]int32{
		"SESSION_SOURCE_UNSPECIFIED": 0,
		"SESSION_SOURCE_JAVA":        1,
		"SESSION_SOURCE_BEDROCK":     2,
	}
)

func (x SessionSource) Enum() *SessionSource {
	p := new(SessionSource)
	*p = x
	return p
}

func (x SessionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsd_relay_v1_relay_proto_enumTypes[2].Descriptor()
}

func (SessionSource) Type() protoreflect.EnumType {
	return &file_mcsd_relay_v1_relay_proto_enumTypes[2]
}

func (x SessionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionSource.Descriptor instead.
func (SessionSource) EnumDescriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

// RegisterRequest carries the relay's tunnel endpoint and active session set
// to the API on startup or reconnect.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnel_endpoint is the host:port the API delivers to Workers in TunnelDial
	// commands so they know where to dial back. Required. RELAY.md Section 5.
	TunnelEndpoint string `protobuf:"bytes,1,opt,name=tunnel_endpoint,json=tunnelEndpoint,proto3" json:"tunnel_endpoint,omitempty"`
	// tunnel_ca_pem is the PEM-encoded CA bundle the API includes in TunnelDial
	// commands so Workers can verify the relay's tunnel certificate. Empty means
	// system roots (public CA). RELAY.md Section 5.
	TunnelCaPem string `protobuf:"bytes,2,opt,name=tunnel_ca_pem,json=tunnelCaPem,proto3" json:"tunnel_ca_pem,omitempty"`
	// active_session_ids is the set of session UUIDs currently live on the
	// relay. The API closes game_session rows that are open but absent from this
	// set — orphan healing after a relay crash. RELAY.md Section 6.
	ActiveSessionIds []string `protobuf:"bytes,3,rep,name=active_session_ids,json=activeSessionIds,proto3" json:"active_session_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetTunnelEndpoint() string {
	if x != nil {
		return x.TunnelEndpoint
	}
	return ""
}

func (x *RegisterRequest) GetTunnelCaPem() string {
	if x != nil {
		return x.TunnelCaPem
	}
	return ""
}

func (x *RegisterRequest) GetActiveSessionIds() []string {
	if x != nil {
		return x.ActiveSessionIds
	}
	return nil
}

// RegisterResponse carries the deployment-level base domain back to the relay
// so it has a single config source for hostname routing. RELAY.md Section 6.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base_domain is the relay's routing domain (e.g. "mc.example.com").
	// Slugs are resolved relative to this; a handshake address that does not
	// end with ".<base_domain>" is treated as unknown. RELAY.md Section 3.
	BaseDomain    string `protobuf:"bytes,1,opt,name=base_domain,json=baseDomain,proto3" json:"base_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetBaseDomain() string {
	if x != nil {
		return x.BaseDomain
	}
	return ""
}

// ResolveJoinRequest asks the API for a routing decision for one incoming
// player connection.
type ResolveJoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// slug is the server identifier extracted from the handshake address by
	// stripping the base_domain suffix. RELAY.md Section 3.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// player_ip is the player's source address as seen by the relay (PII;
	// recorded in game_session). RELAY.md Section 8.
	PlayerIp string `protobuf:"bytes,2,opt,name=player_ip,json=playerIp,proto3" json:"player_ip,omitempty"`
	// intent distinguishes a status ping from a login attempt. RELAY.md
	// Sections 6 and 7.
	Intent        JoinIntent `protobuf:"varint,3,opt,name=intent,proto3,enum=mcsd.relay.v1.JoinIntent" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveJoinRequest) Reset() {
	*x = ResolveJoinRequest{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveJoinRequest) ProtoMessage() {}

func (x *ResolveJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveJoinRequest.ProtoReflect.Descriptor instead.
func (*ResolveJoinRequest) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveJoinRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ResolveJoinRequest) GetPlayerIp() string {
	if x != nil {
		return x.PlayerIp
	}
	return ""
}

func (x *ResolveJoinRequest) GetIntent() JoinIntent {
	if x != nil {
		return x.Intent
	}
	return JoinIntent_JOIN_INTENT_UNSPECIFIED
}

// ResolveJoinResponse carries the routing decision and, for TUNNEL decisions,
// the single-use token the Worker must present. RELAY.md Section 6.
type ResolveJoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// decision is the routing outcome. RELAY.md Section 6.
	Decision JoinDecision `protobuf:"varint,1,opt,name=decision,proto3,enum=mcsd.relay.v1.JoinDecision" json:"decision,omitempty"`
	// token is the single-use 128-bit session token the Worker presents on the
	// tunnel dial-back to identify its connection. Set only when decision is
	// TUNNEL. The token expires in 10 s (RELAY.md Section 4).
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// display_name is the server's human-readable name, used by the relay to
	// synthesize the stopped-server in-protocol response. Set only when
	// decision is STOPPED. RELAY.md Section 7.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// server_id is the API's identifier for the server the player joined, which
	// the relay carries into SessionStart.server_id (the relay cannot resolve
	// slug→server itself). Set only when decision is TUNNEL. RELAY.md Section 8.
	ServerId      string `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveJoinResponse) Reset() {
	*x = ResolveJoinResponse{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveJoinResponse) ProtoMessage() {}

func (x *ResolveJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveJoinResponse.ProtoReflect.Descriptor instead.
func (*ResolveJoinResponse) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveJoinResponse) GetDecision() JoinDecision {
	if x != nil {
		return x.Decision
	}
	return JoinDecision_JOIN_DECISION_UNSPECIFIED
}

func (x *ResolveJoinResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResolveJoinResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResolveJoinResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// ReportSessionsRequest delivers a batch of session lifecycle events to the
// API. Batches are flushed every ~5 s or 100 events. RELAY.md Section 6.
type ReportSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events is the batch of session lifecycle events. RELAY.md Section 6.
	Events        []*SessionEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSessionsRequest) Reset() {
	*x = ReportSessionsRequest{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSessionsRequest) ProtoMessage() {}

func (x *ReportSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSessionsRequest.ProtoReflect.Descriptor instead.
func (*ReportSessionsRequest) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *ReportSessionsRequest) GetEvents() []*SessionEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// ReportSessionsResponse acknowledges a batch. Empty: the relay does not need
// per-event acks, only an error on transient failure to trigger a retry.
type ReportSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSessionsResponse) Reset() {
	*x = ReportSessionsResponse{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSessionsResponse) ProtoMessage() {}

func (x *ReportSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSessionsResponse.ProtoReflect.Descriptor instead.
func (*ReportSessionsResponse) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

// SessionEvent is one lifecycle event in a ReportSessions batch.
// Exactly one of start or end is set. RELAY.md Section 6.
type SessionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SessionEvent_Start
	//	*SessionEvent_End
	Event         isSessionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *SessionEvent) GetEvent() isSessionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SessionEvent) GetStart() *SessionStart {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *SessionEvent) GetEnd() *SessionEnd {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_End); ok {
			return x.End
		}
	}
	return nil
}

type isSessionEvent_Event interface {
	isSessionEvent_Event()
}

type SessionEvent_Start struct {
	// start records a new accepted player session. RELAY.md Section 8.
	Start *SessionStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type SessionEvent_End struct {
	// end records the closing of a session. RELAY.md Section 8.
	End *SessionEnd `protobuf:"bytes,2,opt,name=end,proto3,oneof"`
}

func (*SessionEvent_Start) isSessionEvent_Event() {}

func (*SessionEvent_End) isSessionEvent_Event() {}

// SessionStart records the opening of a player session. Fields mirror the
// game_session table columns (RELAY.md Section 14).
type SessionStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id is the relay-minted UUID, the idempotency key for upserts.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// server_id is the API's identifier for the server the player joined.
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// slug is the hostname label used at join time (historical value; slugs are
	// renameable so this captures what the player typed). RELAY.md Section 14.
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// player_ip is the player's source address as seen by the relay (PII).
	// RELAY.md Section 8.
	PlayerIp string `protobuf:"bytes,4,opt,name=player_ip,json=playerIp,proto3" json:"player_ip,omitempty"`
	// username is the name claimed in the Minecraft Login Start packet.
	// Pre-authentication; with online-mode on, a meaningful-duration session
	// implies a verified identity. Empty string means absent or unparseable
	// (maps to NULL in the game_session table — RELAY.md Sections 7 and 14).
	// RELAY.md Section 8.
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	// player_uuid is the UUID claimed in the Login Start packet (present on
	// protocols that send it; absent on older protocol versions). Empty string
	// means absent or unparseable (maps to NULL in the game_session table —
	// RELAY.md Sections 7 and 14).
	PlayerUuid string `protobuf:"bytes,6,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	// started_at is when the relay accepted the session (relay clock).
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// source is the relay ingress path (Java game listener vs Bedrock tunnel) the
	// session was accepted on, so the history can label the row honestly
	// (issue #1912). Unset means an older relay that predates the field; the API
	// stores it as the legacy/unspecified source.
	Source        SessionSource `protobuf:"varint,8,opt,name=source,proto3,enum=mcsd.relay.v1.SessionSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *SessionStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStart) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SessionStart) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SessionStart) GetPlayerIp() string {
	if x != nil {
		return x.PlayerIp
	}
	return ""
}

func (x *SessionStart) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SessionStart) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *SessionStart) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionStart) GetSource() SessionSource {
	if x != nil {
		return x.Source
	}
	return SessionSource_SESSION_SOURCE_UNSPECIFIED
}

// SessionEnd records the closing of a player session.
type SessionEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id identifies the session being closed (matches a prior
	// SessionStart.session_id).
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// ended_at is when the relay observed the session close (relay clock).
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEnd) Reset() {
	*x = SessionEnd{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnd) ProtoMessage() {}

func (x *SessionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnd.ProtoReflect.Descriptor instead.
func (*SessionEnd) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *SessionEnd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEnd) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// ValidateBedrockTunnelRequest carries the credential a Worker presented on
// its Bedrock QUIC dial-out, for the relay to confirm against the API
// (mcsd.controlplane.v1.OpenBedrockTunnel carries the same three values to
// the Worker).
type ValidateBedrockTunnelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id identifies the local server the dial claims to be for.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// bedrock_port is the public UDP port the dial claims to serve.
	BedrockPort uint32 `protobuf:"varint,2,opt,name=bedrock_port,json=bedrockPort,proto3" json:"bedrock_port,omitempty"`
	// token is the credential the Worker presented on the QUIC dial-out.
	Token         string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBedrockTunnelRequest) Reset() {
	*x = ValidateBedrockTunnelRequest{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBedrockTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBedrockTunnelRequest) ProtoMessage() {}

func (x *ValidateBedrockTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBedrockTunnelRequest.ProtoReflect.Descriptor instead.
func (*ValidateBedrockTunnelRequest) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateBedrockTunnelRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ValidateBedrockTunnelRequest) GetBedrockPort() uint32 {
	if x != nil {
		return x.BedrockPort
	}
	return 0
}

func (x *ValidateBedrockTunnelRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateBedrockTunnelResponse reports whether the presented credential
// matches the tunnel the API currently has open for that server.
type ValidateBedrockTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// valid is true when (server_id, bedrock_port, token) matches the API's
	// current record for an open Bedrock tunnel on that server.
	Valid         bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBedrockTunnelResponse) Reset() {
	*x = ValidateBedrockTunnelResponse{}
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBedrockTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBedrockTunnelResponse) ProtoMessage() {}

func (x *ValidateBedrockTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsd_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBedrockTunnelResponse.ProtoReflect.Descriptor instead.
func (*ValidateBedrockTunnelResponse) Descriptor() ([]byte, []int) {
	return file_mcsd_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateBedrockTunnelResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_mcsd_relay_v1_relay_proto protoreflect.FileDescriptor

const file_mcsd_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x19mcsd/relay/v1/relay.proto\x12\rmcsd.relay.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\x0fRegisterRequest\x12'\n" +
	"\x0ftunnel_endpoint\x18\x01 \x01(\tR\x0etunnelEndpoint\x12\"\n" +
	"\rtunnel_ca_pem\x18\x02 \x01(\tR\vtunnelCaPem\x12,\n" +
	"\x12active_session_ids\x18\x03 \x03(\tR\x10activeSessionIds\"3\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vbase_domain\x18\x01 \x01(\tR\n" +
	"baseDomain\"x\n" +
	"\x12ResolveJoinRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1b\n" +
	"\tplayer_ip\x18\x02 \x01(\tR\bplayerIp\x121\n" +
	"\x06intent\x18\x03 \x01(\x0e2\x19.mcsd.relay.v1.JoinIntentR\x06intent\"\xa4\x01\n" +
	"\x13ResolveJoinResponse\x127\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x1b.mcsd.relay.v1.JoinDecisionR\bdecision\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\"L\n" +
	"\x15ReportSessionsRequest\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.mcsd.relay.v1.SessionEventR\x06events\"\x18\n" +
	"\x16ReportSessionsResponse\"{\n" +
	"\fSessionEvent\x123\n" +
	"\x05start\x18\x01 \x01(\v2\x1b.mcsd.relay.v1.SessionStartH\x00R\x05start\x12-\n" +
	"\x03end\x18\x02 \x01(\v2\x19.mcsd.relay.v1.SessionEndH\x00R\x03endB\a\n" +
	"\x05event\"\xa9\x02\n" +
	"\fSessionStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1b\n" +
	"\tplayer_ip\x18\x04 \x01(\tR\bplayerIp\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1f\n" +
	"\vplayer_uuid\x18\x06 \x01(\tR\n" +
	"playerUuid\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x124\n" +
	"\x06source\x18\b \x01(\x0e2\x1c.mcsd.relay.v1.SessionSourceR\x06source\"b\n" +
	"\n" +
	"SessionEnd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\bended_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"t\n" +
	"\x1cValidateBedrockTunnelRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\fbedrock_port\x18\x02 \x01(\rR\vbedrockPort\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"5\n" +
	"\x1dValidateBedrockTunnelResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid*X\n" +
	"\n" +
	"JoinIntent\x12\x1b\n" +
	"\x17JOIN_INTENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOIN_INTENT_STATUS\x10\x01\x12\x15\n" +
	"\x11JOIN_INTENT_LOGIN\x10\x02*\x7f\n" +
	"\fJoinDecision\x12\x1d\n" +
	"\x19JOIN_DECISION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14JOIN_DECISION_TUNNEL\x10\x01\x12\x19\n" +
	"\x15JOIN_DECISION_STOPPED\x10\x02\x12\x1b\n" +
	"\x17JOIN_DECISION_NOT_FOUND\x10\x03*d\n" +
	"\rSessionSource\x12\x1e\n" +
	"\x1aSESSION_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SESSION_SOURCE_JAVA\x10\x01\x12\x1a\n" +
	"\x16SESSION_SOURCE_BEDROCK\x10\x022\x84\x03\n" +
	"\fRelayService\x12K\n" +
	"\bRegister\x12\x1e.mcsd.relay.v1.RegisterRequest\x1a\x1f.mcsd.relay.v1.RegisterResponse\x12T\n" +
	"\vResolveJoin\x12!.mcsd.relay.v1.ResolveJoinRequest\x1a\".mcsd.relay.v1.ResolveJoinResponse\x12]\n" +
	"\x0eReportSessions\x12$.mcsd.relay.v1.ReportSessionsRequest\x1a%.mcsd.relay.v1.ReportSessionsResponse\x12r\n" +
	"\x15ValidateBedrockTunnel\x12+.mcsd.relay.v1.ValidateBedrockTunnelRequest\x1a,.mcsd.relay.v1.ValidateBedrockTunnelResponseB\xd2\x01\n" +
	"\x11com.mcsd.relay.v1B\n" +
	"RelayProtoP\x01Z[github.com/mmiura-2351/mc-server-dashboard-v2/relay/internal/genproto/mcsd/relay/v1;relayv1\xa2\x02\x03MRX\xaa\x02\rMcsd.Relay.V1\xca\x02\rMcsd\\Relay\\V1\xe2\x02\x19Mcsd\\Relay\\V1\\GPBMetadata\xea\x02\x0fMcsd::Relay::V1b\x06proto3"

var (
	file_mcsd_relay_v1_relay_proto_rawDescOnce sync.Once
	file_mcsd_relay_v1_relay_proto_rawDescData []byte
)

func file_mcsd_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_mcsd_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_mcsd_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsd_relay_v1_relay_proto_rawDesc), len(file_mcsd_relay_v1_relay_proto_rawDesc)))
	})
	return file_mcsd_relay_v1_relay_proto_rawDescData
}

var file_mcsd_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mcsd_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mcsd_relay_v1_relay_proto_goTypes = []any{
	(JoinIntent)(0),                       // 0: mcsd.relay.v1.JoinIntent
	(JoinDecision)(0),                     // 1: mcsd.relay.v1.JoinDecision
	(SessionSource)(0),                    // 2: mcsd.relay.v1.SessionSource
	(*RegisterRequest)(nil),               // 3: mcsd.relay.v1.RegisterRequest
	(*RegisterResponse)(nil),              // 4: mcsd.relay.v1.RegisterResponse
	(*ResolveJoinRequest)(nil),            // 5: mcsd.relay.v1.ResolveJoinRequest
	(*ResolveJoinResponse)(nil),           // 6: mcsd.relay.v1.ResolveJoinResponse
	(*ReportSessionsRequest)(nil),         // 7: mcsd.relay.v1.ReportSessionsRequest
	(*ReportSessionsResponse)(nil),        // 8: mcsd.relay.v1.ReportSessionsResponse
	(*SessionEvent)(nil),                  // 9: mcsd.relay.v1.SessionEvent
	(*SessionStart)(nil),                  // 10: mcsd.relay.v1.SessionStart
	(*SessionEnd)(nil),                    // 11: mcsd.relay.v1.SessionEnd
	(*ValidateBedrockTunnelRequest)(nil),  // 12: mcsd.relay.v1.ValidateBedrockTunnelRequest
	(*ValidateBedrockTunnelResponse)(nil), // 13: mcsd.relay.v1.ValidateBedrockTunnelResponse
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_mcsd_relay_v1_relay_proto_depIdxs = []int32{
	0,  // 0: mcsd.relay.v1.ResolveJoinRequest.intent:type_name -> mcsd.relay.v1.JoinIntent
	1,  // 1: mcsd.relay.v1.ResolveJoinResponse.decision:type_name -> mcsd.relay.v1.JoinDecision
	9,  // 2: mcsd.relay.v1.ReportSessionsRequest.events:type_name -> mcsd.relay.v1.SessionEvent
	10, // 3: mcsd.relay.v1.SessionEvent.start:type_name -> mcsd.relay.v1.SessionStart
	11, // 4: mcsd.relay.v1.SessionEvent.end:type_name -> mcsd.relay.v1.SessionEnd
	14, // 5: mcsd.relay.v1.SessionStart.started_at:type_name -> google.protobuf.Timestamp
	2,  // 6: mcsd.relay.v1.SessionStart.source:type_name -> mcsd.relay.v1.SessionSource
	14, // 7: mcsd.relay.v1.SessionEnd.ended_at:type_name -> google.protobuf.Timestamp
	3,  // 8: mcsd.relay.v1.RelayService.Register:input_type -> mcsd.relay.v1.RegisterRequest
	5,  // 9: mcsd.relay.v1.RelayService.ResolveJoin:input_type -> mcsd.relay.v1.ResolveJoinRequest
	7,  // 10: mcsd.relay.v1.RelayService.ReportSessions:input_type -> mcsd.relay.v1.ReportSessionsRequest
	12, // 11: mcsd.relay.v1.RelayService.ValidateBedrockTunnel:input_type -> mcsd.relay.v1.ValidateBedrockTunnelRequest
	4,  // 12: mcsd.relay.v1.RelayService.Register:output_type -> mcsd.relay.v1.RegisterResponse
	6,  // 13: mcsd.relay.v1.RelayService.ResolveJoin:output_type -> mcsd.relay.v1.ResolveJoinResponse
	8,  // 14: mcsd.relay.v1.RelayService.ReportSessions:output_type -> mcsd.relay.v1.ReportSessionsResponse
	13, // 15: mcsd.relay.v1.RelayService.ValidateBedrockTunnel:output_type -> mcsd.relay.v1.ValidateBedrockTunnelResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mcsd_relay_v1_relay_proto_init() }
func file_mcsd_relay_v1_relay_proto_init() {
	if File_mcsd_relay_v1_relay_proto != nil {
		return
	}
	file_mcsd_relay_v1_relay_proto_msgTypes[6].OneofWrappers = []any{
		(*SessionEvent_Start)(nil),
		(*SessionEvent_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsd_relay_v1_relay_proto_rawDesc), len(file_mcsd_relay_v1_relay_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsd_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_mcsd_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_mcsd_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_mcsd_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_mcsd_relay_v1_relay_proto = out.File
	file_mcsd_relay_v1_relay_proto_goTypes = nil
	file_mcsd_relay_v1_relay_proto_depIdxs = nil
}
