// The Minecraft Server Dashboard v2 relay-to-API contract.
//
// RelayService is served on the API's existing gRPC listener alongside
// WorkerService. All RPCs are relay-initiated (unary); the relay has no
// command inbox. Transport posture matches the Worker: server-side TLS plus a
// shared-secret credential in call metadata, but a separate credential
// (relay.credential) so relay and Worker credentials rotate independently.
//
// See docs/app/RELAY.md Section 6 for the full relay-to-API contract and
// Section 5 for the tunnel contract (TunnelDial lives in the controlplane
// package — RELAY.md Section 5 — because it rides the existing Worker stream).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mcsd/relay/v1/relay.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayService_Register_FullMethodName       = "/mcsd.relay.v1.RelayService/Register"
	RelayService_ResolveJoin_FullMethodName    = "/mcsd.relay.v1.RelayService/ResolveJoin"
	RelayService_ReportSessions_FullMethodName = "/mcsd.relay.v1.RelayService/ReportSessions"
)

// RelayServiceClient is the client API for RelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RelayService is the gRPC service the relay calls on the API. All three RPCs
// are unary (RELAY.md Section 6): the relay has no persistent stream and no
// command inbox; every call is relay-initiated.
type RelayServiceClient interface {
	// Register is called at relay startup and on reconnect. The API stores the
	// relay's tunnel endpoint and CA for use in TunnelDial commands, and closes
	// any game_session rows open but absent from the relay's active set
	// (orphan healing after a relay crash). RELAY.md Section 6.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// ResolveJoin is the per-connection routing decision. The relay calls it
	// once per incoming player connection after parsing the Minecraft handshake.
	// The API returns a routing decision and, on a TUNNEL decision, dispatches
	// a TunnelDial command to the assigned Worker as a side effect (Section 4).
	// RELAY.md Sections 4 and 6.
	ResolveJoin(ctx context.Context, in *ResolveJoinRequest, opts ...grpc.CallOption) (*ResolveJoinResponse, error)
	// ReportSessions delivers batched session lifecycle events (SessionStart and
	// SessionEnd). The API persists them as game_session rows; upsert-on-id
	// makes retries after transient errors safe. RELAY.md Sections 6 and 8.
	ReportSessions(ctx context.Context, in *ReportSessionsRequest, opts ...grpc.CallOption) (*ReportSessionsResponse, error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RelayService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) ResolveJoin(ctx context.Context, in *ResolveJoinRequest, opts ...grpc.CallOption) (*ResolveJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveJoinResponse)
	err := c.cc.Invoke(ctx, RelayService_ResolveJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) ReportSessions(ctx context.Context, in *ReportSessionsRequest, opts ...grpc.CallOption) (*ReportSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSessionsResponse)
	err := c.cc.Invoke(ctx, RelayService_ReportSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServiceServer is the server API for RelayService service.
// All implementations must embed UnimplementedRelayServiceServer
// for forward compatibility.
//
// RelayService is the gRPC service the relay calls on the API. All three RPCs
// are unary (RELAY.md Section 6): the relay has no persistent stream and no
// command inbox; every call is relay-initiated.
type RelayServiceServer interface {
	// Register is called at relay startup and on reconnect. The API stores the
	// relay's tunnel endpoint and CA for use in TunnelDial commands, and closes
	// any game_session rows open but absent from the relay's active set
	// (orphan healing after a relay crash). RELAY.md Section 6.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// ResolveJoin is the per-connection routing decision. The relay calls it
	// once per incoming player connection after parsing the Minecraft handshake.
	// The API returns a routing decision and, on a TUNNEL decision, dispatches
	// a TunnelDial command to the assigned Worker as a side effect (Section 4).
	// RELAY.md Sections 4 and 6.
	ResolveJoin(context.Context, *ResolveJoinRequest) (*ResolveJoinResponse, error)
	// ReportSessions delivers batched session lifecycle events (SessionStart and
	// SessionEnd). The API persists them as game_session rows; upsert-on-id
	// makes retries after transient errors safe. RELAY.md Sections 6 and 8.
	ReportSessions(context.Context, *ReportSessionsRequest) (*ReportSessionsResponse, error)
	mustEmbedUnimplementedRelayServiceServer()
}

// UnimplementedRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRelayServiceServer) ResolveJoin(context.Context, *ResolveJoinRequest) (*ResolveJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveJoin not implemented")
}
func (UnimplementedRelayServiceServer) ReportSessions(context.Context, *ReportSessionsRequest) (*ReportSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSessions not implemented")
}
func (UnimplementedRelayServiceServer) mustEmbedUnimplementedRelayServiceServer() {}
func (UnimplementedRelayServiceServer) testEmbeddedByValue()                      {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServiceServer will
// result in compilation errors.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	// If the following call panics, it indicates UnimplementedRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

func _RelayService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_ResolveJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ResolveJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ResolveJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ResolveJoin(ctx, req.(*ResolveJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_ReportSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ReportSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ReportSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ReportSessions(ctx, req.(*ReportSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayService_ServiceDesc is the grpc.ServiceDesc for RelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcsd.relay.v1.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RelayService_Register_Handler,
		},
		{
			MethodName: "ResolveJoin",
			Handler:    _RelayService_ResolveJoin_Handler,
		},
		{
			MethodName: "ReportSessions",
			Handler:    _RelayService_ReportSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcsd/relay/v1/relay.proto",
}
