#!/usr/bin/env bash
#
# deploy.sh: first-time deployment with interactive .env setup.
#
# If .env does not exist, walks the user through each required variable,
# auto-generating secrets and prompting for host-specific values. Then builds
# all components and deploys via docker compose.
#
# If .env already exists, skips setup and does a full rebuild + deploy
# (equivalent to `make update FORCE=1`).
#
# Usage:
#   make deploy
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
	echo "deploy: not a git checkout." >&2
	exit 1
}
cd "$repo_root"

STAMP_FILE=".last-deploy-sha"

# ── 1. Interactive .env setup ────────────────────────────────────────────────
if [ ! -f .env ]; then
	echo "deploy: .env not found -- starting interactive setup."
	echo ""

	# --- Auto-generated secrets ---
	POSTGRES_PASSWORD="$(openssl rand -base64 32)"
	MCD_API_AUTH__TOKEN__SIGNING_KEY="$(openssl rand -base64 48)"
	MCD_API_CONTROL__WORKER_CREDENTIAL="$(openssl rand -base64 48)"
	MCD_API_STORAGE__OBJECT__ACCESS_KEY="$(openssl rand -hex 16)"
	MCD_API_STORAGE__OBJECT__SECRET_KEY="$(openssl rand -hex 32)"

	# --- Host-specific values (interactive) ---
	read -rp "MCSD_SCRATCH_DIR [/opt/mcsd/scratch]: " MCSD_SCRATCH_DIR
	MCSD_SCRATCH_DIR="${MCSD_SCRATCH_DIR:-/opt/mcsd/scratch}"

	read -rp "API_HTTP_PORT [8000]: " API_HTTP_PORT
	API_HTTP_PORT="${API_HTTP_PORT:-8000}"

	read -rp "API_HTTP_BIND_IP (127.0.0.1=loopback, 0.0.0.0=all) [127.0.0.1]: " API_HTTP_BIND_IP
	API_HTTP_BIND_IP="${API_HTTP_BIND_IP:-127.0.0.1}"

	read -rp "Storage backend (object/fs) [object]: " STORAGE_BACKEND
	STORAGE_BACKEND="${STORAGE_BACKEND:-object}"
	if [ "$STORAGE_BACKEND" != "object" ] && [ "$STORAGE_BACKEND" != "fs" ]; then
		echo "deploy: ERROR -- invalid storage backend '${STORAGE_BACKEND}'; must be 'object' or 'fs'." >&2
		exit 1
	fi

	COMPOSE_PROFILES=""
	MCD_API_STORAGE__BACKEND_LINE=""
	S3_ACCESS_KEY_LINE="MCD_API_STORAGE__OBJECT__ACCESS_KEY=${MCD_API_STORAGE__OBJECT__ACCESS_KEY}"
	S3_SECRET_KEY_LINE="MCD_API_STORAGE__OBJECT__SECRET_KEY=${MCD_API_STORAGE__OBJECT__SECRET_KEY}"

	if [ "$STORAGE_BACKEND" = "fs" ]; then
		COMPOSE_PROFILES=""
		MCD_API_STORAGE__BACKEND_LINE="MCD_API_STORAGE__BACKEND=fs"
		S3_ACCESS_KEY_LINE="MCD_API_STORAGE__OBJECT__ACCESS_KEY="
		S3_SECRET_KEY_LINE="MCD_API_STORAGE__OBJECT__SECRET_KEY="
	else
		COMPOSE_PROFILES="object"
	fi

	# --- Relay ---
	MCD_API_RELAY__ENABLED="false"
	MCD_API_RELAY__CREDENTIAL=""
	MCD_API_RELAY__BASE_DOMAIN=""
	MCD_RELAY_TUNNEL_PUBLIC_ENDPOINT=""
	MCD_RELAY_TLS_DIR="/etc/mcsd/relay"
	MCD_WORKER_GAME_BIND_IP=""

	read -rp "Enable relay? (yes/no) [no]: " RELAY_ENABLED
	RELAY_ENABLED="${RELAY_ENABLED:-no}"

	if [ "$RELAY_ENABLED" = "yes" ]; then
		MCD_API_RELAY__ENABLED="true"
		MCD_API_RELAY__CREDENTIAL="$(openssl rand -base64 48)"
		MCD_WORKER_GAME_BIND_IP="127.0.0.1"

		if [ -n "$COMPOSE_PROFILES" ]; then
			COMPOSE_PROFILES="${COMPOSE_PROFILES},relay"
		else
			COMPOSE_PROFILES="relay"
		fi

		read -rp "MCD_API_RELAY__BASE_DOMAIN (e.g. mc.example.com): " MCD_API_RELAY__BASE_DOMAIN
		if [ -z "$MCD_API_RELAY__BASE_DOMAIN" ]; then
			echo "deploy: ERROR -- relay base domain is required when relay is enabled." >&2
			exit 1
		fi

		read -rp "MCD_RELAY_TUNNEL_PUBLIC_ENDPOINT (e.g. host:25665): " MCD_RELAY_TUNNEL_PUBLIC_ENDPOINT
		if [ -z "$MCD_RELAY_TUNNEL_PUBLIC_ENDPOINT" ]; then
			echo "deploy: ERROR -- relay tunnel public endpoint is required when relay is enabled." >&2
			exit 1
		fi

		read -rp "MCD_RELAY_TLS_DIR [/etc/mcsd/relay]: " input_tls_dir
		MCD_RELAY_TLS_DIR="${input_tls_dir:-/etc/mcsd/relay}"
	fi

	# --- Cloudflare Tunnel ---
	CLOUDFLARE_TUNNEL_TOKEN=""

	read -rp "Enable Cloudflare Tunnel? (yes/no) [no]: " TUNNEL_ENABLED
	TUNNEL_ENABLED="${TUNNEL_ENABLED:-no}"

	if [ "$TUNNEL_ENABLED" = "yes" ]; then
		read -rp "Cloudflare Tunnel token: " CLOUDFLARE_TUNNEL_TOKEN
		if [ -z "$CLOUDFLARE_TUNNEL_TOKEN" ]; then
			echo "deploy: ERROR -- tunnel token is required when tunnel is enabled." >&2
			exit 1
		fi

		if [ -n "$COMPOSE_PROFILES" ]; then
			COMPOSE_PROFILES="${COMPOSE_PROFILES},tunnel"
		else
			COMPOSE_PROFILES="tunnel"
		fi
	fi

	# --- Write .env ---
	cat > .env << ENVEOF
# Environment for the single-host compose deployment.
# Generated by scripts/deploy.sh. .env is gitignored -- it holds secrets
# and host-specific values. Never commit it.

# --- PostgreSQL ------------------------------------------------------------
POSTGRES_USER=mcsd
POSTGRES_DB=mcsd
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# --- API secrets -----------------------------------------------------------
MCD_API_AUTH__TOKEN__SIGNING_KEY=${MCD_API_AUTH__TOKEN__SIGNING_KEY}
MCD_API_CONTROL__WORKER_CREDENTIAL=${MCD_API_CONTROL__WORKER_CREDENTIAL}

# --- Storage backend -------------------------------------------------------
COMPOSE_PROFILES=${COMPOSE_PROFILES}
${S3_ACCESS_KEY_LINE}
${S3_SECRET_KEY_LINE}
${MCD_API_STORAGE__BACKEND_LINE:+${MCD_API_STORAGE__BACKEND_LINE}}

# --- Worker / container driver ---------------------------------------------
MCSD_SCRATCH_DIR=${MCSD_SCRATCH_DIR}
${MCD_WORKER_GAME_BIND_IP:+MCD_WORKER_GAME_BIND_IP=${MCD_WORKER_GAME_BIND_IP}}

# --- Relay -----------------------------------------------------------------
MCD_API_RELAY__CREDENTIAL=${MCD_API_RELAY__CREDENTIAL}
MCD_API_RELAY__ENABLED=${MCD_API_RELAY__ENABLED}
MCD_API_RELAY__BASE_DOMAIN=${MCD_API_RELAY__BASE_DOMAIN}
MCD_RELAY_TUNNEL_PUBLIC_ENDPOINT=${MCD_RELAY_TUNNEL_PUBLIC_ENDPOINT}
MCD_RELAY_TLS_DIR=${MCD_RELAY_TLS_DIR}

# --- Cloudflare Tunnel -----------------------------------------------------
CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

# --- Published host ports --------------------------------------------------
API_HTTP_PORT=${API_HTTP_PORT}
API_HTTP_BIND_IP=${API_HTTP_BIND_IP}
ENVEOF

	echo ""
	echo "deploy: .env written."
else
	echo "deploy: .env exists -- skipping interactive setup."
fi

# ── 2. Preflight ─────────────────────────────────────────────────────────────
scripts/deploy_preflight.sh

# ── 2b. Pull latest main ────────────────────────────────────────────────────
echo "deploy: pulling latest main..."
git pull --ff-only origin main

# ── 3. Build all components (api -> relay -> worker) ─────────────────────────
build_version="$(git describe --tags --always 2>/dev/null || echo 0.0.0-dev)"

echo "deploy: building api..."
sg docker -c "DOCKER_BUILDKIT=1 docker build --network=host -t mcsd-api:dev -f api/Dockerfile ."

echo "deploy: building relay..."
sg docker -c "DOCKER_BUILDKIT=1 docker build --network=host --build-arg VERSION=${build_version} -t mcsd-relay:dev ./relay"

echo "deploy: building worker..."
sg docker -c "DOCKER_BUILDKIT=1 docker build --network=host --build-arg VERSION=${build_version} -t mcsd-worker:dev ./worker"

# ── 4. Deploy ─────────────────────────────────────────────────────────────────
echo "deploy: starting services..."
sg docker -c "docker compose up -d"

# ── 5. Healthcheck ────────────────────────────────────────────────────────────
api_port="${API_HTTP_PORT:-8000}"
if [ -f .env ]; then
	api_port="$(grep -E '^API_HTTP_PORT=' .env | cut -d= -f2 | tr -d '[:space:]')"
	api_port="${api_port:-8000}"
fi

echo "deploy: waiting for API healthcheck (port ${api_port})..."
ok=0
for i in $(seq 1 30); do
	if curl -sf "http://localhost:${api_port}/api/healthz" > /dev/null 2>&1; then
		ok=1
		break
	fi
	sleep 2
done

if [ "$ok" -ne 1 ]; then
	echo "deploy: ERROR -- API healthcheck failed after 60s." >&2
	exit 1
fi
echo "deploy: API healthcheck passed."

# ── 6. Stamp deployed commit ─────────────────────────────────────────────────
head_sha="$(git rev-parse HEAD)"
echo "$head_sha" > "$STAMP_FILE"
echo "deploy: deployed ${head_sha:0:7} successfully."
